---
- name: Render helm values template for RIC
  ansible.builtin.template:
    src: "{{ workspace }}/{{ component_type }}/code/any/cac/helm_values_template-ric.yaml.j2"
    dest: "/root/{{ helm_release_name }}-values-ric.yaml"

- name: Render helm values template for Portainer
  ansible.builtin.template:
    src: "{{ workspace }}/{{ component_type }}/code/any/cac/helm_values_template-portainer.yaml.j2"
    dest: "/root/{{ helm_release_name }}-values-portainer.yaml"

- name: Deploy RIC helm
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    name: "{{ helm_release_name }}"
    chart_ref: oci://registry-1.docker.io/iswirelesspoland/ric-helm-charts
    chart_version: 0.1.0
    namespace: "{{ helm_release_name }}"
    create_namespace: true
    values_files:
    - "/root/{{ helm_release_name }}-values-ric.yaml"

- name: Deploy Portainer helm
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    name: "{{ helm_release_name }}"
    chart_ref: oci://registry-1.docker.io/iswirelesspoland/portainer-helm-charts
    chart_version: 0.1.0
    namespace: "{{ helm_release_name }}"
    create_namespace: true
    values_files:
    - "/root/{{ helm_release_name }}-values-portainer.yaml"

- name: Wait until all pods are Running
  ansible.builtin.command: "kubectl wait pod --all --for=condition=Ready -n {{ helm_release_name }} --kubeconfig /etc/rancher/rke2/rke2.yaml --timeout=240s"
