# This is information about infrastructure, systems and available equipment that has a static nature and 
# may differ between different sites. 
# It is a way to simplify and homogenize the definition of components and their deployments.
#
# All first level variables SHOULD start by the prefix site_
#
# SITE: UMA
#

site_hipervisor: one #one, vmware, etc ...
site_networks:
  - id: 0                    # ID from OpenNebula Networks List
    name: External Network   # Representative Name
    if_name: br_281_srv      # Interface that support this Network
  - id: 13
    name: NTN Network
    if_name: br_120
site_vxlan_if: br_281_srv     # It must be the name of the interface on which the new vxlan will be created

site_s3_server:
  endpoint: "http://10.11.28.95:9000"
  bucket: "demo"
  #key: "terraform.tfstate"
  #access_key="AKIAIOSFODNN7EXAMPLE"
  #secret_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  region: "main"
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_region_validation: true
  force_path_style: true



