---
  # TODO: Find a way to make this block have idempotency
- name: "Write terraform manifest with the custom outputs"
  ansible.builtin.lineinfile:
    path: "{{ workspace }}/.terraform/tf-custom_outputs.tf"
    line: |
      {% for item in custom_outputs %}
      output "{{ item.key }}" {
        description = "{{ item.description }}"
        value       = "{{ item.value }}"
      }
      {% endfor %}
    insertafter: EOF
    state: present
    create: true

- name: Load outputs into the .tfstate
  community.general.terraform:
    project_path: "{{ workspace }}/.terraform/"
    state: "present"

- name: Upload terraform manifest to S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: put
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')}}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY')}}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ tn_id }}/tf-custom_outputs.tf"
    src: "{{ workspace }}/.terraform/tf-custom_outputs.tf"
    encrypt: no
