---
- name: "Write terraform manifest with the custom outputs"
  ansible.builtin.blockinfile:
    path: "{{ workspace }}/.terraform/tf-custom_outputs.tf"
    create: true
    append_newline: true
    prepend_newline: true
    block: |
      {% for item in custom_outputs %}
      output "{{ item.key }}" {
        description = "{{ item.description }}"
        value       = "{{ item.value }}"
      }
      {% endfor %}

- name: Load outputs into the .tfstate
  community.general.terraform:
    project_path: "{{ workspace }}/.terraform/"
    state: "present"
  ignore_errors: true
- name: Upload terraform manifest to S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: put
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')}}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY')}}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ tn_id }}/tf-custom_outputs.tf"
    src: "{{ workspace }}/.terraform/tf-custom_outputs.tf"
    encrypt: no
