---
- name: Prepare opennebula provider terraform manifest
  ansible.builtin.copy:
    src: "{{ workspace }}/.global/iac/{{ site_hypervisor }}/opennebula_provider_v1.4.tf"
    dest: "{{ workspace }}/.terraform/opennebula_provider_v1.4.tf"

- name: Prepare AWS s3 backend terraform manifest
  ansible.builtin.template:
    src: "{{ workspace }}/.global/iac/backend.tf.j2"
    dest: "{{ workspace }}/.terraform/backend.tf"

- name: "Get terraform manifests from previous deployed components"
  ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/common_tasks/s3_download.yaml"

- name: "Prepare {{ component_type }} terraform manifest"
  ansible.builtin.template:
    src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/iac/terraform.tf.j2"
    dest: "{{ workspace }}/.terraform/tf-{{ entity_name }}.tf"
  when: terraform_template | default(false)
