---
- name: "STAGE 1: Apply IAC to deploy the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Prepare terraform working directory
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_workdir.yaml"

    - name: Terraform apply
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_apply.yaml"


- name: "STAGE 2: Prepare to access the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Retrieve terraform outputs
      ansible.builtin.shell:
      args:
        chdir: "{{ workspace }}/.terraform/"
        cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
        executable: /bin/bash
      register: terraform_outputs
      changed_when: false

    - name: Set Terraform outputs as playbook facts
      ansible.builtin.set_fact:
        bastion_ip: "{{ (terraform_outputs.stdout | from_json)['tn_bastion-ips'][site_networks_id.default | string] }}"
        tn_ssh_public_key: "{{ (terraform_outputs.stdout | from_json)['tn_ssh_public_key'] }}"
        id: "{{ (terraform_outputs.stdout | from_json)[entity_name + '-id'] }}"
        cluster_roles: "{{ (terraform_outputs.stdout | from_json)[entity_name + '-roles'] }}"

    - name: Fetch cluster node IDs
      ansible.builtin.set_fact:
        node_ids: >-
          {{
            node_ids | default({}) | combine({
              (item.0.name + '_' + item.0.nodes.index(item.1) | string): item.1 | string
            })
          }}
      loop: "{{ cluster_roles | subelements('nodes', skip_missing=True) }}"

    - name: Fetch cluster node IPs
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/01_pre/node_ip.yaml"
      loop: "{{ node_ids | dict2items }}"

    - name: Add new VMs to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "{{ entity_name }}-{{ item.key }}"
        groups: "OneKE_VMs"
        ansible_host: "{{ item.value }}"
        ansible_ssh_common_args: "-J jenkins@{{ bastion_ip }}{% if not item.key.startswith('vnf') %},root@{{ node_ips.vnf_0 }}{% else %}{% endif %}"
        ansible_user: "root"
      loop: "{{ node_ips | dict2items }}"

    - name: Add new VMs to SSH config file in the Jenkins-master for debugging purposes
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/01_pre/ssh_config.yaml"
      loop: "{{ node_ips | dict2items }}"

    - name: Fetch master metadata
      community.general.one_vm:
        instance_ids: "{{ node_ids.master_0 | int }}"
        api_url: "{{ lookup('ansible.builtin.env', 'OPENNEBULA_ENDPOINT') }}"
        api_username: "{{ lookup('ansible.builtin.env', 'OPENNEBULA_USERNAME') }}"
        api_password: "{{ lookup('ansible.builtin.env', 'OPENNEBULA_PASSWORD') }}"
      register: master_metadata
    - name: Extract kubeconfig file from master metadata
      ansible.builtin.set_fact:
        kubeconfig: "{{ master_metadata.instances[0].attributes.ONEKE_KUBECONFIG }}"

    - name: Create kubeconfig
      ansible.builtin.copy:
        content: "{{ kubeconfig | b64decode }}"
        dest: "{{ workspace }}/{{ component_type }}/code/{{ entity_name }}.kubeconfig"
        mode: "644"


- name: "STAGE 3: Apply CAC to prepare the component"
  hosts: "OneKE_VMs"
  gather_facts: false
  tasks:
    - name: Set site ssh key as authorized in jenkins user
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ item }}"
      loop:
        - "{{ hostvars['localhost'].get('site_admin_ssh_public_key', '') }}"
      when: item != ''

    - name: Create new user for experimenter access in alpine
      ansible.builtin.user:
        name: tnuser
        shell: /bin/bash
        groups: wheel
      when: "'vnf' in inventory_hostname"

    - name: Create new user for experimenter access in ubuntu
      ansible.builtin.user:
        name: tnuser
        shell: /bin/bash
        groups: sudo
      when: "'vnf' not in inventory_hostname"

    - name: Set TN ssh key as authorized in new user
      ansible.posix.authorized_key:
        user: tnuser
        state: present
        key: "{{ item }}"
      loop:
        - "{{ hostvars['localhost']['tn_ssh_public_key'] }}"

    - name: Apply extra Helm charts
      when: inventory_hostname == hostvars['localhost']['entity_name'] + '-master_0'
      block:
        - name: Apply ingress-nginx helm chart
          ansible.builtin.include_tasks: >-
            {{ workspace }}/{{ component_type }}/code/{{ hostvars['localhost']['site_hypervisor'] }}/cac/02_install/install_nginx_controller.yaml

        - name: Apply Skooner helm chart
          ansible.builtin.include_tasks: >-
            {{ workspace }}/{{ component_type }}/code/{{ hostvars['localhost']['site_hypervisor'] }}/cac/02_install/install_skooner_dashboard.yaml

        - name: Apply nginx Ingress for the longhorn dashboard
          ansible.builtin.include_tasks: >-
            {{ workspace }}/{{ component_type }}/code/{{ hostvars['localhost']['site_hypervisor'] }}/cac/02_install/install_longhorn_dashboard.yaml
          when: hostvars['localhost']['one_oneKE_longhorn'] == "YES"

- name: "STAGE 4: Publish execution results"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Upload kubeconfig to S3
      amazon.aws.s3_object:
        endpoint_url: "{{ site_s3_server.endpoint }}"
        mode: put
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        bucket: "{{ site_s3_server.bucket }}"
        object: "{{ tn_id }}/kconf-{{ entity_name }}.kubeconfig"
        src: "{{ workspace }}/{{ component_type }}/code/{{ entity_name }}.kubeconfig"
        encrypt: false
        validate_certs: false

    - name: Define OneKE metadata dictionary
      ansible.builtin.set_fact:
        oneke_metadata_dict: >-
          {
            'external_vnet': '{{ one_oneKE_external_vnet }}',
            'internal_vnet': '{{ one_oneKE_internal_vnet }}',
            'version': '{{ one_oneKE_version }}',
            'multus': '{{ one_oneKE_multus }}',
            'cni_plugin': '{{ one_oneKE_cni_plugin }}',
            'cilium_range': '{{ one_oneKE_cilium_range }}',
            'metallb_range': '{{ one_oneKE_metallb_range }}',
            'longhorn': '{{ one_oneKE_longhorn }}',
            'dns': '{{ one_oneKE_dns }}',
            'nginx_passthough': '{{ one_oneKE_nginx_passthough }}'
          }

    - name: Publish node IDs and IPs as a terraform outputs"
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/custom_tf_outputs.yaml"
      vars:
        custom_outputs:
          - key: "{{ entity_name }}-node_ids"
            value: "{{ node_ids }}"
          - key: "{{ entity_name }}-node_ips"
            value: "{{ node_ips }}"
          - key: "{{ entity_name }}-metadata"
            value: "{{ oneke_metadata_dict }}"

    - name: Publish execution results to TNLCM
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/publish_ok_results.yaml"
      vars:
        output:
          id: "{{ id | b64encode }}"
          node_ids: "{{ node_ids | b64encode }}"
          node_ips: "{{ node_ips | b64encode }}"
          metadata_dict: "{{ oneke_metadata_dict | b64encode }}"
          kubeconfig: "{{ kubeconfig | b64encode }}"
          skooner_token: "{{ hostvars[entity_name + '-master_0']['skooner_token']['stdout'] | b64encode }}"
