---
- name: Wait for VPN server to be ready
  become: true
  ansible.builtin.wait_for:
    path: "/root/client.conf"
    state: present

- name: Get remote VPN config file content
  become: true
  ansible.builtin.slurp:
    src: "/root/client.conf"
  register: client_tunnel

- name: Debug returned client config
  ansible.builtin.debug:
    msg: "{{ client_tunnel['content'] | b64decode }}"   
  when: debug
