---
- name: Generate an ed25519 ssh keypair
  openssh_keypair:
    comment: "TrialNetwork@{{ tn_id }}"
    force: false
    path: "/tmp/id_ed25519"
    type: ed25519

- name: Slurp public ssh key
  ansible.builtin.slurp:
    src: "/tmp/id_ed25519.pub"
  register: ssh_public_key

- name: Slurp private ssh key
  ansible.builtin.slurp:
    src: "/tmp/id_ed25519"
  register: ssh_private_key

- name: Set ssh keys as authorized in the nodes
  ansible.posix.authorized_key:
    user: "{{ site_jenkins_ssh_user }}"
    state: present
    key: "{{ item }}"
  loop:
    - "{{ site_admin_ssh_public_key }}"
    - "{{ ssh_public_key }}"
