---
- name: "Set VM Resources needed for component"
  ansible.builtin.set_fact:
    one_elcm_cpu: "{{ one_elcm_cpu }}"
    one_elcm_memory: "{{ one_elcm_memory }}"
    one_elcm_disk: "{{ one_elcm_disk }}"

- name: Overwrite again with explicit values from the input file
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/input_file.yaml"