- name: Prepare the workspace with necessary enviromental variables
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Debug workspace
      ansible.builtin.debug:
        var: workspace

    - name: Display all variables
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

    # - name: Load enviromental variables from different sources
    #   ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/mix_variables_tasks.yaml"
