- name: Prepare the workspace with necessary enviromental variables
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ ansible_env.WORKSPACE }}/.global/cac/tasks/load_variables.yaml"
