---
- name: Append new commponent's name and IP into a .ssh/config.d/ file
  community.general.ssh_config:
    host: "{{ tn_id }}-{{ entity_name }}"
    hostname:  "{{ ips[access_vnet_id] | default('ERROR_ASSIGNING_IP', true) }}"
    identity_file: "~/.ssh/misc-{{ tn_id }}-id_ed25519"
    remote_user: "tnuser"
    ssh_config_file: "{{ workspace }}/ssh_config"
    state: present
  register: tnuser_ssh_config
