---
- name: Load site-specific variables
  ansible.builtin.include_vars:
    file: "{{ workspace }}/6G-Sandbox-Sites/{{ deployment_site }}/core.yaml"

- name: Load private component-specific variables for any hypervisor
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/any/private.yaml"
  failed_when: false

- name: Load private component-specific variables for the site hypervisor
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/{{ site_hypervisor }}/private.yaml"
  failed_when: false

- name: Load public component-specific variables from input file
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/input_file.yaml"
