- name: Load variables from site
  ansible.builtin.include_vars:
    file: "{{ workspace }}/6G-Sandbox-Sites/.sites/{{ deployment_site }}/values.yaml"

- name: Load private variables from component
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_name }}/private/values.yaml"

- name: Check if component file with tnlcm related variables exists
  stat:
    path: "{{ workspace }}/{{ component_name }}/private/tnlcm_vars.yaml"
  register: file_exits
- name: Load private TNLCM related variables from component
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_name }}/private/tnlcm_vars.yaml"
  when: file_exits.stat.exists  
