---
- name: Generate OK markdown response
  ansible.builtin.template:
    src: "{{ workspace }}/{{ component_type }}/result_templates/ok_result.md.j2"
    dest: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.md"

- name: Encode OK response into base64 
  ansible.builtin.slurp:
    src: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.md"
  register: ok2markdown

- name: Generate OK json response
  ansible.builtin.template:
    src: "{{ workspace }}/.global/json_templates/ok_result.json.j2"
    dest: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.json"

- name: Debug OK json response
  ansible.builtin.debug:
    msg: "{{ workspace }}/.global/json_templates/ok_result.json.j2"
  when: debug

- name: Send OK json response to TNLCM
  ansible.builtin.uri:
    url: "{{ tnlcm_callback }}"
    method: POST
    body_format: json
    src: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.json"
  register: tnlcm_post
  ignore_errors: true
