- name: Generate responses for success
  when: not result.failed
  block:
  - name: Generate markdown response for success
    ansible.builtin.template:
      src: "{{ workspace }}/{{ component_name }}/results/result_ok.md.j2"
      dest: "{{ workspace }}/{{ component_name }}/results/result_ok.{{ component_name }}.{{ tn_id }}.md"

  - name: Encode markdown OK file into base64 
    ansible.builtin.slurp:
      src: "{{ workspace }}/{{ component_name }}/results/result_ok.{{ component_name }}.{{ tn_id }}.md"
    register: markdown2ok

  - name: Generate markdown response for success in JSON
    ansible.builtin.template:
      src: "{{ workspace }}/{{ component_name }}/results/result_ok.json.j2"
      dest: "{{ workspace }}/{{ component_name }}/results/result_ok.json"

  - name: POST result to TNLCM with OK
    ansible.builtin.uri:
      url: "{{ tnlcm_callback }}"
      method: POST
      body_format: json
      src: "{{ workspace }}/{{ component_name }}/results/result_ok.json"
    register: output
    ignore_errors: true 


- name: Generate responses for not success
  when: result.failed
  block:
  - name: Generate markdown response for not success
    ansible.builtin.template:
      src: "{{ workspace }}/{{ component_name }}/results/result_nok.md.j2"
      dest: "{{ workspace }}/{{ component_name }}/results/result_nok.{{ component_name }}.{{ tn_id }}.md"

  - name: Encode markdown NOK file into base64 
    ansible.builtin.slurp:
      src: "{{ workspace }}/{{ component_name }}/results/result_nok.{{ component_name }}.{{ tn_id }}.md"
    register: markdown2nok

  - name: Generate markdown response for not success in JSON
    ansible.builtin.template:
      src: "{{ workspace }}/{{ component_name }}/results/result_nok.json.j2"
      dest: "{{ workspace }}/{{ component_name }}/results/result_nok.json"

  - name: POST result to TNLCM with NOK
    ansible.builtin.uri:
      url: "{{ tnlcm_callback }}"
      method: POST
      body_format: json
      src: "{{ workspace }}/{{ component_name }}/results/result_nok.json"
    ignore_errors: true
