
    - name: Generate markdown response for success
      template:
        src: "{{ workspace }}/{{ component_name }}/results/result_ok.md.j2"
        dest: "{{ workspace }}/{{ component_name }}/results/result_ok.{{ component_name }}.{{ tn_id }}.md"
      when: not result.failed

    - name: Generate markdown response for not success
      template:
        src: "{{ workspace }}/{{ component_name }}/results/result_nok.md.j2"
        dest: "{{ workspace }}/{{ component_name }}/results/result_nok.{{ component_name }}.{{ tn_id }}.md"
      when: result.failed

    - name: Encode markdown OK file into base64 
      ansible.builtin.slurp:
        src: "{{ workspace }}/{{ component_name }}/results/result_ok.{{ component_name }}.{{ tn_id }}.md"
      register: markdown
      when: not result.failed

    - name: Encode markdown NOK file into base64 
      ansible.builtin.slurp:
        src: "{{ workspace }}/{{ component_name }}/results/result_nok.{{ component_name }}.{{ tn_id }}.md"
      register: markdown
      when: result.failed

    - name: Display result variable
      ansible.builtin.debug:
        msg: "{{ markdown | to_json }}"

    - name: Generate markdown response for success in JSON
      template:
        src: "{{ workspace }}/{{ component_name }}/results/result_ok.json.j2"
        dest: "{{ workspace }}/{{ component_name }}/results/result_ok.json"
      when: not result.failed

    - name: Generate markdown response for not success in JSON
      template:
        src: "{{ workspace }}/{{ component_name }}/results/result_nok.json.j2"
        dest: "{{ workspace }}/{{ component_name }}/results/result_nok.json"
      when: result.failed      
  
    - name: POST result to TNLCM with OK
      uri:
        url: "{{ tnlcm_callback }}"
        method: POST
        body_format: json
        src: "{{ workspace }}/{{ component_name }}/results/result_ok.json"
      register: output
      when: not result.failed
      ignore_errors: true 

    - name: Display result variable
      ansible.builtin.debug:
        msg: "{{ output | to_json }}"

    - name: POST result to TNLCM with NOK
      uri:
        url: "{{ tnlcm_callback }}"
        method: POST
        body_format: json
        src: "{{ workspace }}/{{ component_name }}/results/result_nok.json"
      when: result.failed
      ignore_errors: true