---
- name: Upload terraform manifest to S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: put
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')}}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY')}}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ tn_id }}/{{ item.dest | basename }}"
    src: "{{ item.dest }}"
    encrypt: false
  loop: "{{ terraform_manifests.results }}"
  when: terraform_apply.failed is defined and terraform_apply.failed == false

- name: Generate OK markdown response
  ansible.builtin.template:
    src: "{{ workspace }}/{{ component_type }}/result_templates/ok_result.md.j2"
    dest: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.md"

- name: Encode OK response into base64
  ansible.builtin.slurp:
    src: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.md"
  register: ok2markdown

- name: Generate OK json response
  ansible.builtin.template:
    src: "{{ workspace }}/.global/json_templates/ok_result.json.j2"
    dest: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.json"

- name: Debug OK json response
  ansible.builtin.debug:
    msg: "{{ workspace }}/.global/json_templates/ok_result.json.j2"
  when: debug

- name: Send OK json response to TNLCM
  ansible.builtin.uri:
    url: "{{ tnlcm_callback }}"
    method: POST
    body_format: json
    src: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.json"
  register: tnlcm_post
  failed_when: false

- name: Send OK markdown response to S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: put
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ tn_id }}/ok_result-{{ entity_name }}.md"
    src: "{{ workspace }}/{{ component_type }}/code/ok_result-{{ entity_name }}.md"
    encrypt: false
