---
- name: "Make a PUT request to the tn_bastion's route-manager-api"
  ansible.builtin.uri:
    url: "http://{{ endpoint }}:8172/routes"
    method: PUT
    headers:
      accept: application/json
      Authorization: "Bearer {{ token }}"
      Content-Type: application/json
    body_format: json
    body: >
      {
        "to": "{{ item.to }}",
        "via": "{{ item.via }}",
        "create_at": "{{ start_time }}",
        "delete_at": "{{ stop_time }}"
      }
    return_content: yes
  register: api_response

- name: Display response content
  debug:
    var: api_response.content
  when: debug
