---
- name: "Make a POST request to the tn_bastion's route-manager-api"
  ansible.builtin.uri:
    url: "http://{{ endpoint }}:8172/routes"
    method: POST
    headers:
      accept: application/json
      Authorization: "{{ site_routemanager.token }}"
      Content-Type: application/json
    body_format: json
    body: >
      {
        "destination": "{{ item.destination }}",
        "gateway": "{{ item.gateway }}",
        "create_at": "{{ start_time }}",
        "delete_at": "{{ stop_time }}"
      }
    return_content: yes
  register: api_response

- name: Display response content
  debug:
    var: api_response.content
  when: debug
