---
- name: "Make a PUT request to a route-manager-api"
  ansible.builtin.uri:
    url: "http://{{ endpoint }}:8172/routes/"
    method: PUT
    headers:
      accept: application/json
      Authorization: "Bearer {{ token }}"
      Content-Type: application/json
    body_format: json
    body: "{{
      {
        'to': item.to,
        'via': item.via
      } 
      | combine( {'create_at': start_time} if start_time is defined else {} )
      | combine( {'delete_at': stop_time} if stop_time is defined else {} )
      | to_json }}"
    return_content: true
    status_code: [200,201]
  register: api_response

- name: Display response content
  debug:
    var: api_response.content
  when: debug
