- name: Get list of files from S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: list
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')}}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY')}}"
    bucket: "{{ site_s3_server.bucket }}"
    prefix: "{{ tn_id }}"
    marker: "{{ tn_id }}"
    validate_certs: false
  register: s3_bucket_items

- name: Download S3 files
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: get
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')}}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY')}}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ item }}"
    dest: "{{ workspace }}/.terraform/{{ item | basename }}"
    validate_certs: false
  when: item.endswith('.tf')
  with_items: "{{ s3_bucket_items.s3_keys }}"
