---
- name: Create directory for terraform manifests
  ansible.builtin.file:
    path: "{{ workspace }}/.terraform"
    state: directory
    mode: '0755'

- name: "Prepare {{ site_hypervisor }} provider terraform manifest"
  ansible.builtin.copy:
    src: "{{ workspace }}/.global/iac/{{ site_hypervisor }}/provider.tf"
    dest: "{{ workspace }}/.terraform/{{ site_hypervisor }}_provider.tf"

- name: Prepare AWS s3 backend terraform manifest
  ansible.builtin.template:
    src: "{{ workspace }}/.global/iac/backend.tf.j2"
    dest: "{{ workspace }}/.terraform/backend.tf"

- name: "Get terraform manifests from previous deployed components"
  ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/s3_download.yaml"

- name: terraform init
  ansible.builtin.command: "terraform -chdir={{ workspace }}/.terraform/ init"
