---
### Module ssh_config has limited options and doesnt allow to specify identity files that doesn't exist
- name: Append new component's name and IP into a .ssh/config.d/ file
  ansible.builtin.blockinfile:
    path: "{{ workspace }}/.terraform/misc-{{ tn_id }}-ssh_config"
    marker: "# BEGIN {{ tn_id }}-{{ entity_name }} CONFIG"
    create: true
    block: |
      Host espantosin-{{ entity_name }}
          hostname {{ ips[access_vnet_id] | default('ERROR_ASSIGNING_IP', true) }}
          user tnuser
          identity_file: "~/.ssh/misc-{{ tn_id }}-id_ed25519"
    insertafter: EOF
  register: tnuser_ssh_config
