---
- name: "STAGE 1: Set new routes in route-manager-api and tn_bastion"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Prepare terraform working directory
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_workdir.yaml"

    - name: Retrieve terraform outputs
      ansible.builtin.shell:
      args:
        chdir: "{{ workspace }}/.terraform/"
        cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
        executable: /bin/bash
      register: terraform_outputs
      changed_when: false

    - name: Set Terraform outputs as playbook facts
      ansible.builtin.set_fact:
        bastion_ip: "{{ (terraform_outputs.stdout | from_json)['tn_bastion-ips'][site_networks_id.default | string] }}"
        tn_routemanager_token: "{{ (terraform_outputs.stdout | from_json)['tn_routemanager_token'] }}"
    - name: Set start of lease time and date with RFC 3339 section 5.6 format
      ansible.builtin.set_fact:
        current_timestamp: >-
          {{
            any_iswireless_radio_start_time | default(lookup('pipe', 'date -u +"%Y-%m-%dT%H:%M:%SZ"'), true)
          }}
    - name: Set end of lease time and date with RFC 3339 section 5.6 format
      ansible.builtin.set_fact:
        ending_timestamp: >-
          {{
            lookup('pipe', 'date -u -d "' ~ current_timestamp ~ ' + ' ~ any_iswireless_radio_duration ~ ' seconds" +"%Y-%m-%dT%H:%M:%SZ"')
          }}

    - name: Tasks for iswireless_radio with external CU
      when: not any_iswireless_radio_ru_du
      block:
        - name: "Stablish route in tn_bastion to the CU through the site's route-manager-api"
          ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/routemanager_add.yaml"
          vars:
            endpoint: "{{ bastion_ip }}"
            token: "{{ tn_routemanager_token }}"
            start_time: "{{ current_timestamp }}"
            stop_time: "{{ ending_timestamp }}"
          loop:
            - { to: "{{ site_available_components.iswireless_radio.cu_ip }}", via: "{{ site_iswireless_routemanager.api_endpoint }}" }

        - name: "Stablish routes in the site's route-manager-api to the 5G core through tn_bastion"
          ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/routemanager_add.yaml"
          vars:
            endpoint: "{{ site_iswireless_routemanager.api_endpoint }}"
            token: "{{ site_iswireless_routemanager.token }}"
            start_time: "{{ current_timestamp }}"
            stop_time: "{{ ending_timestamp }}"
            core_metadata: "{{ (terraform_outputs.stdout | from_json)[any_iswireless_radio_linked_5gcore + '-5gcore_metadata'] }}"
            # TODO: Hardcoded vnet component name. Please remove this line after component testing
            _vnet_internal_net: "{{ (terraform_outputs.stdout | from_json)['vnet-internal-net'] }}"
          loop:
            # TODO: Hardcoded vnet component name. Please remove this line after component testing
            - { to: "{{ _vnet_internal_net }}", via: "{{ bastion_ip }}" }
            # TODO: Desirable final routes. Uncomment themm when everything is tested
            # - { to: "{{ core_metadata['amf_n2_ip'] }}", via: "{{ bastion_ip }}" }
            # - { to: "{{ core_metadata['upf_n3_ip'] }}", via: "{{ bastion_ip }}" }

    - name: Tasks for iswireless_radio in RU-DU mode, with a CU component
      when: any_iswireless_radio_ru_du
      block:
        - name: "Stablish route in tn_bastion to the DU through the site's route-manager-api"
          when: not any_iswireless_radio_ru_du
          ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/routemanager_add.yaml"
          vars:
            endpoint: "{{ bastion_ip }}"
            token: "{{ tn_routemanager_token }}"
            start_time: "{{ current_timestamp }}"
            stop_time: "{{ ending_timestamp }}"
          loop:
            - { to: "{{ site_available_components.iswireless_radio.du_ip }}", via: "{{ site_iswireless_routemanager.api_endpoint }}" }

        - name: "Stablish routes in the site's route-manager-api to the CU through tn_bastion"
          when: not any_iswireless_radio_ru_du
          ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/routemanager_add.yaml"
          vars:
            endpoint: "{{ site_iswireless_routemanager.api_endpoint }}"
            token: "{{ site_iswireless_routemanager.token }}"
            start_time: "{{ current_timestamp }}"
            stop_time: "{{ ending_timestamp }}"
            # TODO: Ensure this output is defined in cu_k8s. NO DICTIONARY
            cu_ip: "{{ (terraform_outputs.stdout | from_json)[any_iswireless_radio_linked_cu + '-cu_ip'] }}"
          loop:
            - { to: "{{ cu_ip }}", via: "{{ bastion_ip }}" }


- name: "STAGE 2: Recreate the necessary gNB containers, and prepare access to the tn_bastion"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Add the bastion to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "bastion"
        ansible_host: "{{ bastion_ip }}"
        ansible_user: "jenkins"



# TODO: All 5G Core components already add firewall exceptions themselves (nftables_add.yaml)
# TODO: cu_k8s and cu_k8s should also add the exceptions they need for their IPs in the bastion
- name: "STAGE 3: Access tn_bastion to set firewall exceptions"
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Write firewall exceptions for the route-manager-api and the CU of your site
      when: not any_iswireless_radio_ru_du
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/nftables_add.yaml"
      vars:
        fw_exceptions:
          - "{{ site_iswireless_routemanager.api_endpoint }}"
          - "{{ site_available_components.iswireless_radio.cu_ip }}"
        nat_exceptions:
          - "{{ site_available_components.iswireless_radio.cu_ip }}"

    - name: Write firewall exception for the route-manager-api and the DU of your site
      when: any_iswireless_radio_ru_du
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/nftables_add.yaml"
      vars:
        fw_exceptions:
          - "{{ site_iswireless_routemanager.api_endpoint }}"
          - "{{ site_available_components.iswireless_radio.du_ip }}"
        nat_exceptions:
          - "{{ site_available_components.iswireless_radio.du_ip }}"


- name: "STAGE 4: Publish execution results"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Define gnb_metadata dictionary in the CU-DU scenario
      when: not any_iswireless_radio_ru_du
      ansible.builtin.set_fact:
        gnb_metadata_dict: >-
          {
            'linked_5gcore': '{{ any_iswireless_radio_linked_5gcore | default('None') }}',
          }
    - name: Define gnb_metadata dictionary in the RU-DU scenario
      when: any_iswireless_radio_ru_du
      ansible.builtin.set_fact:
        gnb_metadata_dict: >-
          {
            'linked_5gcore': '{{ (terraform_outputs.stdout | from_json)[any_iswireless_radio_linked_cu + '-linked_5gcore'] }}',
            'n2_ip': '{{ (terraform_outputs.stdout | from_json)[any_iswireless_radio_linked_cu + '-n2_ip'] }}',
            'n3_ip': '{{ (terraform_outputs.stdout | from_json)[any_iswireless_radio_linked_cu + '-n3_ip'] }}'
          }
    - name: Set custom terraform outputs for future components
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/custom_tf_outputs.yaml"
      vars:
        custom_outputs:
          - key: "{{ entity_name }}-gnb_metadata"
            value: "{{ gnb_metadata_dict }}"

    - name: Publish execution results to TNLCM and S3 object storage
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/publish_ok_results.yaml"
