---
- name: check if Caddy is already installed
  stat:
    path: /usr/local/bin/caddy_server
  register: caddy_bin

- name: download caddy
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/caddyserver/caddy/releases/download/v2.10.0/caddy_2.10.0_linux_amd64.tar.gz"
    dest: /usr/local/bin/
    mode: "+x"
    remote_src: true
  when: not caddy_bin.stat.exists

- name: rename
  become: true
  ansible.builtin.command:
    cmd: mv /usr/local/bin/caddy /usr/local/bin/caddy_server
    removes: /usr/local/bin/caddy

- name: create caddy directory
  file:
    path: "/etc/open5gcore/caddy"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    mode: 0660
    dest: /etc/open5gcore/caddy/
  loop:
    - "caddy/Caddyfile"
    - "caddy/index.html"
  become: true

- name: install caddy service
  copy:
    src: "caddy-open5gcore.service"
    dest: /etc/systemd/system/
  register: systemdfiles

- name: "systemd daemon-reload"
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemdfiles.changed

- name: enable & start services
  service:
    name: "caddy-open5gcore"
    state: started
    enabled: true
