- name: Create new SSH config file about new Appliance inside the Jenkins host
  community.general.ssh_config:
    host: "{{ tn_id }}-{{ one_component_name }}"
    hostname: "{{ vm_internal_ip }}" 
    remote_user: root
    proxyjump: "{{ tn_id }}-tn-bastion"
    ssh_config_file: "/var/lib/jenkins/.ssh/config.d/{{ tn_id }}"
    state: present
