# Generate Infrastructure Manifests
- name: "Define Terraform {{ site_hypervisor }} provider file"
  ansible.builtin.copy:
    src: "{{ workspace }}/.global/iac/providers.tf"    # suggestion: rename "providers.tf" file to one_provider_v1.3.tf to make it easier to select the chosen provider with variables, Also future possibility to select provider version
    dest: "{{ workspace }}/.terraform/one_provider_v1.3.tf"

- name: Define Terraform backup file to store the terraform.tfstate inside a s3 backend
  template:
    src: "{{ workspace }}/.global/iac/backend.tf.j2"
    dest: "{{ workspace }}/.terraform/backend.tf"

- name: "Define the Terraform manifest file for the {{ component_type }} component"
  template:
    src: "{{ workspace }}/{{ component_type }}/private/{{ site_hypervisor }}/iac/terraform.tf.j2"  # suggestion: rename to component_manifest.tf.j2, or something more specific
    dest: "{{ workspace }}/.terraform/{{ one_component_name }}_{{ ansible_date_time.epoch }}.tf"  # date makes the file unique already.

# Brough from the manifest.yaml file.
- name: Download Terraform manifest from previous TN components
  ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/download_bucket_content_tasks.yaml"           # download_bucket_content.yaml file not used ???