---
- name: Render helm values template
  ansible.builtin.template:
    src: "{{ workspace }}/{{ component_type }}/code/any/cac/helm_values_template.yaml.j2"
    dest: "/root/{{ hostvars['localhost']['entity_name'] }}-helm_values.yaml"

- name: Deploy Open5Gs helm
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    name: "{{ hostvars['localhost']['entity_name'] | regex_replace('_', '') | lower }}"
    chart_ref: oci://registry-1.docker.io/gradiantcharts/open5gs
    chart_version: 2.2.6
    namespace: "{{ hostvars['localhost']['entity_name'] | regex_replace('_', '') | lower }}"
    create_namespace: true
    values_files:
    - "/root/{{ hostvars['localhost']['entity_name'] }}-helm_values.yaml"

- name: Wait for all pods to be Running
  ansible.builtin.command: kubectl wait pod --all --for=condition=Ready -n open5gs --kubeconfig /etc/rancher/rke2/rke2.yaml --timeout=1200s

- name: Wait till all pods are Running
  kubernetes.core.k8s_info:
    kind: Pod
    wait: yes
    name: pod-not-yet-created
    namespace: "{{ hostvars['localhost']['entity_name'] | regex_replace('_', '') | lower }}"
    wait_sleep: 5      # default
    wait_timeout: 120  # default