---
- name: Load site-specific variables
  ansible.builtin.include_vars:
    file: "{{ workspace }}/6G-Sandbox-Sites/.sites/{{ ansible_env.DEPLOYMENT_SITE }}/values.yaml"

- name: Load private component-specific variables
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ ansible_env.LIBRARY_COMPONENT_NAME }}/variables/{{ site_hypervisor }}/private.yaml"

- name: Load public component-specific variables from input file
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ ansible_env.LIBRARY_COMPONENT_NAME }}/variables/input_file.yaml"

- name: Load pipeline-specific variables from Jenkins parameters
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ ansible_env.LIBRARY_COMPONENT_NAME }}/variables/pipeline_parameters.yaml"
