# TODO: Inform collection "amazon.aws >= 7.5.0" is required in ansible-galaxy
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/index.html#plugins-in-amazon-aws
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/s3_object_module.html

- name: Get list of files from S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: list
    access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
    secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
    bucket: "{{ site_s3_server.bucket }}"
    prefix: "{{ tn_id }}"
    marker: "{{ tn_id }}"
  register: s3_bucket_items

- name: Download S3 files
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: get
    access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
    secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ item }}"
    dest: "{{ workspace }}/{{ library_component_name }}/code/{{ site_hypervisor }}/iac/{{ item | basename }}"
  when: item.endswith('.tf')
  with_items: "{{ s3_bucket_items.s3_keys }}"
