- name: Upload terraform manifest to S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: put
    access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
    secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ tn_id }}/manifest-{{ library_component_name }}{{
           '-'+entity_name if entity_name is defined else '' }}.tf"
    src: "{{ workspace }}/{{ library_component_name }}/code/{{ site_hypervisor }}/iac/{{ library_component_name }}{{
           '-'+entity_name if entity_name is defined else '' }}.tf"
    encrypt: no


- name: Send OK markdown response to S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: put
    access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
    secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ tn_id }}/ok_result-{{ tn_id }}-{{ library_component_name }}-{{
           '-'+entity_name if entity_name is defined else '' }}.md"
    src: "{{ workspace }}/{{ library_component_name }}/code/ok_result-{{ tn_id }}-{{ library_component_name }}-{{
           '-'+entity_name if entity_name is defined else '' }}.md"
    encrypt: no
