---
- name: "STAGE 1: Apply IAC to deploy the component"
  hosts: localhost
  gather_facts: false
  tasks:


    - name: Add the corresponding k8s master to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "{{ entity_name }}-{{ item.key }}-master"
        ansible_host: "{{ item.value }}"
        ansible_ssh_common_args: "-J {{ site_jenkins_user }}@{{ bastion_ip }}{% if item.key != 'vnf' %},root@{{ node_ips.vnf }}{% else %}{% endif %}"
        ansible_user: "root"
















# STAGE 3: Task on oneKE Master

# STAGE 4: Execute manifest
- name: Setup Jenkins to access oneKE Cluster
  hosts: localhost
  tasks:

    - name: Helm install
      ansible.builtin.include_tasks: "./cac/helm_install.yaml"



# STAGE 5: Generate Responses and save manifest a config files
- name: Finishing deployment
  hosts: localhost
  tasks:

      # "output": {
    #     "one_open5gs_mcc": "{{ one_open5gs_mcc | b64encode }}",
    #     "one_open5gs_mnc": "{{ one_open5gs_mnc | b64encode }}",
    #     "one_open5gs_tac": "{{ one_open5gs_tac | b64encode }}",
    #     "one_open5gs_s_nssai_sst": "{{ one_open5gs_s_nssai_sst | b64encode }}",
    #     "one_open5gs_s_nssai_sd": "{{ one_open5gs_s_nssai_sd | b64encode }}",
    #     "one_open5gs_amf_ip": "{{ one_open5gs_amf_ip | b64encode }}",
    #     "one_open5gs_upf_ip": "{{ one_open5gs_upf_ip | b64encode }}"
    # }



    - name: Publish execution results
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/publish_results_tasks.yaml"

    - name: Upload deployment manifest
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/upload_manifest_to_folder_tasks.yaml"
