################################################
##
## Component private variables
##
## Variables that should be necessary 
## for the deployment but are not available 
## to the experimenter
##
################################################

subdomain_webui_dashboard: "open5gs-dashboard"
