- name: Post configuration Playbook
  hosts: bastion
  tasks:
    - name: Wait for VPN server ready
      become: true
      ansible.builtin.wait_for:
        path: "/root/client.conf"
        state: present
      register: result

    - name: Get remote VPN config file content
      become: true
      ansible.builtin.slurp:
        src: "/root/client.conf"
      register: client

    - name: Debug returned client config
      ansible.builtin.debug:
        msg: "{{ client | b64decode }}"      
