---
- name: "STAGE 1: Apply IAC to deploy the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Terraform apply
      community.general.terraform:
        project_path: "{{ workspace }}/.terraform/"
        state: "present"
        force_init: true
      failed_when: false
      register: terraform_apply

    - name: Check if terraform apply return code
      block:
        - name: Publish stderr terraform output to TNLCM
          ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/common_tasks/publish_ok_results.yaml"

        - name: Stop pipeline execution
          ansible.builtin.meta: end_play
      when: terraform_apply.failed


- name: "STAGE 2: Publish execution results"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Retrieve terraform outputs
      ansible.builtin.shell:
      args:
        chdir: "{{ workspace }}/.terraform/"
        cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
        executable: /bin/bash
      register: terraform_outputs
      changed_when: false

    - name: Set Terraform outputs as facts
      ansible.builtin.set_fact:
        id: "{{ (terraform_outputs.stdout | from_json)[entity_name + '-id'] }}"

    - name: Merge all component component outputs into one "output" variable
      ansible.builtin.set_fact:
        output:
          id: "{{ id | b64encode }}"

    - name: Publish execution results to TNLCM
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/common_tasks/publish_ok_results.yaml"

    - name: Upload markdown info to S3 storage
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/common_tasks/s3_upload.yaml"
