# START MANDATORY BLOCK
- name: Mix variables from different sources
  ansible.builtin.import_playbook: "../../../.global/cac/mix_variables.yaml"
# END MANDATORY BLOCK    

# Generate Infrastructure Manifests
- name: Generate Terraform backend manifests
  hosts: localhost
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: "../../../.global/iac/providers.tf"
        dest: iac/providers.tf
    - name: Generate Terraform manifest
      template:
        src: "../../../.global/iac/backend.tf.j2"
        dest: iac/backend.tf

- name: Generate VXLAN component manifests
  hosts: localhost
  tasks:
    - name: Generate Terraform manifest
      template:
        src: iac/terraform.tf.j2
        dest: "iac/{{ component_name }}_{{ ansible_date_time.epoch }}.tf"

- name: Download Terraform previous manifest
  ansible.builtin.import_playbook: "../../../.global/cac/download_bucket_content.yaml" 
  vars:
    dst_folder: "../../{{ component_name}}/private/{{ site_hipervisor }}/iac"
