# Generate Infrastructure Manifests

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: "{{ workspace }}/.global/iac/providers.tf"
    dest: iac/providers.tf
- name: Generate Terraform s3 backend manifest
  template:
    src: "{{ workspace }}/.global/iac/backend.tf.j2"
    dest: iac/backend.tf
- name: Generate VXLAN component manifests
  template:
    src: iac/terraform.tf.j2
    dest: "iac/{{ component_name }}_{{ ansible_date_time.epoch }}.tf"
