# Receive variables from TN file descriptor and load into memory
- name: Prepare execution context
  hosts: localhost
  tags: always
  tasks:
    - name: Load variables from config
      ansible.builtin.include_vars:
        dir: ../
        files_matching: values.yaml

    - name: Load variables from config
      ansible.builtin.include_vars:
        dir: /tmp
        files_matching: "{{tn_id}}_{{component_name}}_vars.yml"

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars['localhost']        

# Generate Manifests
- name: Generate VXLAN component manifests
  hosts: localhost
  tasks:
    - name: Generate Terraform manifest
      template:
        src: iac/terraform.tf.j2
        dest: iac/terraform.tf



