- name: Generate installation manifest from templates
  ansible.builtin.import_playbook: "../../../.global/cac/mix_variables.yaml"

# Generate Manifests
- name: Generate VXLAN component manifests
  hosts: localhost
  tasks:
    - name: Generate Terraform manifest
      template:
        src: iac/terraform.tf.j2
        dest: iac/terraform.tf



