# START MANDATORY BLOCK
- name: Mix variables from different sources
  ansible.builtin.import_playbook: "../../../.global/cac/mix_variables.yaml"
# END MANDATORY BLOCK    

# Generate Infrastructure Manifests
- name: Generate Terraform backend manifests
  hosts: localhost
  tasks:
    - name: Generate Terraform manifest
      template:
        src: ../../../.global/iac/backend.tf.j2
        dest: iac/backend.tf

- name: Generate VXLAN component manifests
  hosts: localhost
  tasks:
    - name: Generate Terraform manifest
      template:
        src: iac/terraform.tf.j2
        dest: iac/terraform.tf



