---
- name: "Set public SSH key as a terraform output"
  ansible.builtin.copy:
    content: |
      output "ssh_public_key" {
        description = "SSH Public Key"
        value       = "{{ hostvars[entity_name]['ssh_public_key']['content'] | b64decode }}"
      }
    dest: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/iac/tf-ssh_public_key.tf"
  when: not terraform_apply.failed
- name: Load output into the .tfstate
  community.general.terraform:
    project_path: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/iac/"
    state: "present"
  ignore_errors: true
  when: not terraform_apply.failed
- name: Upload terraform manifest to S3
  amazon.aws.s3_object:
    endpoint_url: "{{ site_s3_server.endpoint }}"
    mode: put
    access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')}}"
    secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY')}}"
    bucket: "{{ site_s3_server.bucket }}"
    object: "{{ tn_id }}/tf-ssh_public_key.tf"
    src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/iac/tf-ssh_public_key.tf"
    encrypt: no
