# ---- UPF-P4 Controller Configuration Parameters ----
constants:
  # UP function identifier
  FQDN_UP: "up"

  # IPv4 and MACs addresses of the control plane interface (N4)
  SMF_IPV4_N4: "127.0.0.4"
  UPF_IPV4_N4: "127.0.0.7"
  #SMF_MAC_N4: "00:aa:bb:00:00:42"
  SMF_MAC_N4: "00:00:00:00:00:00"
  #UPF_MAC_N4: "00:aa:bb:00:00:41"
  UPF_MAC_N4: "00:00:00:00:00:00"

  # IPv4 and MACs addresses of the different data plane interfaces (N3, N6 & N9)
  ENB_IPV4_N3: "10.0.3.2"
  ENB_IPV4_N3_2: "10.0.32.2"
  UPF2_IPV4_N9: "10.0.9.2"
  DN_IPV4_N6: "10.0.6.2"

  UPF_IPV4_N3: "10.0.3.1"
  UPF_IPV4_N3_2: "10.0.32.1"
  UPF_IPV4_N9: "10.0.9.1"
  UPF_IPV4_N6: "10.0.6.1"
  UPF_IPV4_N6_2: "10.0.62.1"

  #ENB_MAC_N3: "00:aa:bb:00:00:32"
  ENB_MAC_N3: "00:0c:29:8b:74:9d"
  ENB_MAC_N3_2: "00:aa:bb:00:02:32"
  UPF2_MAC_N9: "00:aa:bb:00:00:92"
  DN_MAC_N6: "00:0c:29:1d:76:76"

  #UPF_MAC_N3: "00:aa:bb:00:00:31"
  UPF_MAC_N3: "00:0c:29:ac:eb:ed"
  UPF_MAC_N3_2: "00:aa:bb:00:02:31"
  UPF_MAC_N9: "00:aa:bb:00:00:91"
  UPF_MAC_N6: "00:0c:29:ac:eb:d9"
  UPF_MAC_N6_2: "00:aa:bb:00:02:61"

  # IP UE pool subnet
  subnet_IPv4: "10.45.0.0/16"

  # Controller interfaces
  CONTROLLER_INTF_N4: 'lo'

  # Data Plane P4 interfaces
  GRPC_ADDR: '127.0.0.1:9559'
