title: "Sample TNLCM descriptor for Grafana"
description: "Grafana to visualize data obtained from an experiment"
trial_network:
  tn_vxlan:
    type: "tn_vxlan"
    dependencies: []
    input: {}
  tn_bastion:
    type: "tn_bastion"
    dependencies:
      - "tn_vxlan"
    input: {}
  grafana-v11:
    type: "grafana"
    name: "v11"
    dependencies:
      - "tn_vxlan"
      - "tn_bastion"
    input:
      one_grafana_version: "11.6.0"
      one_grafana_password: "adminadmin"
