- name: Append new commponent's name and IP into a .ssh/config.d/ file
  community.general.ssh_config:
    host: "{{ tn_id }}-tn_bastion"
    hostname: "{{ ips[one_bastion_reachable_network] | default('ERROR_ASSIGNING_IP') }}"
    remote_user: "{{ site_jenkins_ssh_user }}"
    identity_file: "/var/lib/jenkins/.ssh/id_ed25519"
    ssh_config_file: "/var/lib/jenkins/.ssh/config.d/{{ tn_id }}"
    state: present
