# START MANDATORY BLOCK
- name: Generate installation manifest from templates
  hosts: localhost
  tasks: 
    - name: Mix variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/mix_variables_tasks.yaml"
# END MANDATORY BLOCK    

# STAGE 1: Prepare manifest from templates
- name: Generate installation manifest from templates
  hosts: localhost
  tasks: 
    - name: Generate installation manifest from templates
      ansible.builtin.include_tasks: ./{{ site_hypervisor }}/prepare.yaml

# STAGE 2: Execute manifest
- name: Infrastructure Tasks
  hosts: localhost
  tasks:
    - name: Download Terraform manifest from previos TN components
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/download_bucket_content_tasks.yaml" 
          
    - name: Execute terraform apply
      community.general.terraform:
        project_path: './{{ site_hypervisor }}/iac/'
        state: "present"
        force_init: true
      register: result 

    - name: Display result variable
      ansible.builtin.debug:
        var: result

    - name: Display result variable
      ansible.builtin.debug:
        msg: "{{ result | to_json }}"

    - name: Display result variable
      ansible.builtin.debug:
        var: result.outputs

    - name: Get Terraform Outputs
      ansible.builtin.debug:
        msg: "The VXLAN ID is {{ result.outputs[one_vxlan_name + \"_vxlan_id\"].value }}"
      when: not result.failed

    - name: Generate markdown response for success
      template:
        src: "{{ workspace }}/{{ component_name }}/doc/result_ok.md.j2"
        dest: "{{ workspace }}/{{ component_name }}/doc/result_ok.{{ ansible_date_time.epoch }}.md"
      when: not result.failed

    - name: Generate markdown response for not success
      template:
        src: "{{ workspace }}/{{ component_name }}/doc/result_nok.md.j2"
        dest: "{{ workspace }}/{{ component_name }}/doc/result_nok.{{ ansible_date_time.epoch }}.md"
      when: result.failed

    - name: Upload Terraform manifest
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/upload_manifest_to_folder_tasks.yaml"
      when: not result.failed

    - name: Inform TNLCM with component deployment outputs
      ansible.builtin.debug:
        msg: "Upload to Terraform states repository {{ tnlcm_callback }}"

    - name: Encode markdown OK file into base64 
      ansible.builtin.slurp:
        src: "{{ workspace }}/{{ component_name }}/doc/result_ok.{{ ansible_date_time.epoch }}.md"
      register: markdown
      when: not result.failed

    - name: Encode markdown NOK file into base64 
      ansible.builtin.slurp:
        src: "{{ workspace }}/{{ component_name }}/doc/result_nok.{{ ansible_date_time.epoch }}.md"
      register: markdown
      when: result.failed

    - name: POST result to TNLCM with OK
      uri:
        url: "{{ tnlcm_callback }}"
        method: POST
        body_format: json
        body: |
          {
            "tn_vxlan_id": "{{ result.outputs[one_vxlan_name + \"_vxlan_id\"].value }}",
            "result": "ok",
            "result_msg": "{{ markdown['content'] }}"
          }
      when: not result.failed
      ignore_errors: true 

    - name: POST result to TNLCM with NOK
      uri:
        url: "{{ tnlcm_callback }}"
        method: POST
        body_format: json
        body: |
          {
            "result": "nok",
            "result_msg": " {{ markdown['content'] }}"
          }
      when: result.failed
      ignore_errors: true