# FLOW: INSTALL

# STAGE 1: Prepare manifest from templates

- name: Generate installation manifest from templates
  ansible.builtin.import_playbook: ./one/prepare.yaml

# STAGE 2: Execute manifest

- name: Create virtual infrastructure
  hosts: localhost
  tasks:
    - name: Execute terraform apply
      community.general.terraform:
        project_path: './one/iac/'
        state: "present"
        force_init: true
      register: result 


