################################################
##
## Component private variables
##
## Variables that should be necessary 
## for the deployment but are not available 
## to the experimenter
##
################################################

one_bastion_name: "tn_bastion"
one_group: "oneadmin"   # change to "6G-Sandbox" in the future
memory: 256M
disk: 5G
vcpu: 2
one_bastion_wireguard_allowed_networks: "192.168.199.0/24"
one_component_networks: 
  - 0           # First one is the default network
  - VXLAN_ID    # VXLAN SHOULD BE CREATED BEFORE 
