--- 
apiVersion: v1
kind: Service
metadata: 
  {{- if .Values.messageBroker.shared_ip }}
  annotations:
    metallb.universe.tf/address-pool: nginx
    metallb.universe.tf/allow-shared-ip: shared-ip
  {{- end }}

  labels: 
    group: onemnef
  name: message-broker
spec: 
  ports: 
    - 
      name: mqttssl
      port: 8883
      protocol: TCP
      targetPort: 8883
  selector: 
    app: message-broker
  type: LoadBalancer
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: message-broker
    group: onemnef
  name: message-broker
spec: 
  selector: 
    matchLabels: 
      app: message-broker
  template: 
    metadata: 
      labels: 
        app: message-broker
        group: onemnef
    spec: 
      containers: 
        -
          image: "{{ .Values.global.registry }}{{ .Values.messageBroker.image}}:{{ .Values.messageBroker.tag }}"
          imagePullPolicy: Always
          name: message-broker
          ports: 
            - 
              containerPort: 8883
              name: mqttssl
      imagePullSecrets: 
        - 
          name: {{ .Values.global.imagePullSecrets.name }}