apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecrets.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"dockerhub.mobilesandbox.cloud:9443\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" (tpl .Values.global.harborUser .) (tpl .Values.global.harborPassword .) (printf "%s:%s" (tpl .Values.harborUser .) (tpl .Values.harborPassword .) | b64enc) | b64enc }}
