--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: session-required-qos
    group: onemnef
  name: session-required-qos
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: session-required-qos
  template: 
    metadata: 
      labels: 
        app: session-required-qos
        group: onemnef
    spec: 
      containers: 
        - 
          image: "{{ .Values.global.registry }}{{ .Values.sessionRequiredQosMs.image}}:{{ .Values.sessionRequiredQosMs.tag }}"
          imagePullPolicy: Always
          name: session-required-qos
          workingDir: /home/ONEmNEF/API-microservices/Nnef_AsSessionWithQos
          args:
          - "python3 main.py"
          command: 
          - sh
          - "-c"
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: session-required-qos-config

---
apiVersion: v1
data:
  config.init: |
    [general]
    logs = True
    heartbeat = False
    ; DEBUG, INFO, WARNING, ERROR, CRITICAL
    logger_name = AsSesReqQos
    log_level = DEBUG
    log_location = logs
    log_to_console = True
    log_to_file = False

    [logger]
    log_level = DEBUG
    log_to_file = False
    log_file_path = ''

    [mqtt]
    ssl = True
    verify_ssl = False
    ca_path = '/home/ONEmNEF/certs/ca.pem'
    host = {{ .Values.global.mqtt_host }}
    port = {{ .Values.global.mqtt_port }}
    retries = 1025
    workers = 6

kind: ConfigMap
metadata:
  name: session-required-qos-config
  namespace: onemnef