{% raw %}
dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"
{% endraw %}

populate:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs-dbctl
    tag: 0.10.3
    pullPolicy: IfNotPresent
  initCommands: #[]
  # example of initCommands:
  - open5gs-dbctl add_ue_with_slice {{ one_open5gs_mcc }}{{ one_open5gs_mnc }}{{ one_open5gs_msin }} {{ one_open5gs_key }} {{ one_open5gs_opc }} {{ one_open5gs_one_open5gs_apn }} {{ one_open5gs_s_nssai_sst }} {{ one_open5gs_s_nssai_sd }}

# Common
mongodb:
  enabled: true
  auth:
    enabled: false
smf:
  enabled: true
upf:
  enabled: true
webui:
  enabled: true

# 4G
hss:
  enabled: false
  mongodb:
    enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
  mongodb:
    enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false

smf:
  config:
    pcrf:
      enabled: false
# 5G
amf:
  enabled: true
ausf:
  enabled: true
bsf:
  enabled: true
nrf:
  enabled: true
nssf:
  enabled: true
pcf:
  enabled: true
  mongodb:
    enabled: false
scp:
  enabled: true
  mongodb:
    enabled: false
udm:
  enabled: true
udr:
  enabled: true
  mongodb:
    enabled: false

amf:
  config:
    guamiList:
      - plmn_id:
          mcc: "{{ one_open5gs_mcc }}"
          mnc: "{{ one_open5gs_mnc }}"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "{{ one_open5gs_mcc }}"
          mnc: "{{ one_open5gs_mnc }}"
        tac: [ {{ one_open5gs_tac }} ]
    plmnList:
      - plmn_id:
          mcc: "{{ one_open5gs_mcc }}"
          mnc: "{{ one_open5gs_mnc }}"
        s_nssai:
          - sst: {{ one_open5gs_s_nssai_sst }}
            sd: "{{ one_open5gs_s_nssai_sd }}"
    networkName: "open5gs"
  services:
    ngap:
      type: LoadBalancer
      loadBalancerIP: "{{ one_open5gs_amf_ip }}"

nrf:
  config:
    servingList:
      - plmn_id:
          mcc: "{{ one_open5gs_mcc }}"
          mnc: "{{ one_open5gs_mnc }}"

upf:
  config:
    upf:
      gtpu:
        advertise: "{{ one_open5gs_upf_ip }}"
  services:
    gtpu:
      type: LoadBalancer
      loadBalancerIP: "{{ one_open5gs_upf_ip }}"


nssf:
  config:
    nsiList:
    - uri: ""
      sst: {{ one_open5gs_s_nssai_sst }}
      sd: "{{ one_open5gs_s_nssai_sd }}"

webui:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: "{{ one_open5gs_webui_subdomain }}.{{ tn_id}}.{{ site_domain }}"
