- name: Add routes in bastion
  vars:
    o5gcore_tn_vxlan_ip: "{{ hostvars['localhost']['ips'][hostvars['localhost']['access_vnet_id']]}}"
  ansible.builtin.shell: "ip route add {{ item }} || ip route change {{ item }}"
  with_items:
    - "{{ one_open5gcore_vm_ue_subnet }} via {{ o5gcore_tn_vxlan_ip }}"
  become: true

#- name: add Routes via networkctl
#  vars:
#    bastion_tn_vxlan_if: "eth1"
#    o5gcore_tn_vxlan_ip: "{{ hostvars['localhost']['ips'][hostvars['localhost']['access_vnet_id']]}}" #ips[access_vnet_id]
