---
- name: "STAGE 1: Prepare to access a previous target component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Prepare terraform working directory
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_workdir.yaml"

    - name: Retrieve terraform outputs
      ansible.builtin.shell:
      args:
        chdir: "{{ workspace }}/.terraform/"
        cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
        executable: /bin/bash
      register: terraform_outputs
      changed_when: false

    - name: Set Terraform outputs as playbook facts
      ansible.builtin.set_fact:
        bastion_ip: "{{ (terraform_outputs.stdout | from_json)['tn_bastion-ips'][site_networks_id.default | string] }}"
        tn_dns_token: "{{ (terraform_outputs.stdout | from_json)['tn_dns_token'] }}"
        tn_routemanager_token: "{{ (terraform_outputs.stdout | from_json)['tn_routemanager_token'] }}"
        node_ips: "{{ (terraform_outputs.stdout | from_json)[one_open5gs_k8s_target + '-node_ips'] }}"
        domain_name: >-
          {{
            (
              (component_type  | regex_replace('_', '') | lower) ~ '-' ~
              (custom_name     | regex_replace('_', '') | lower) ~ '.' ~
              (tn_id           | regex_replace('_', '') | lower) ~ '.' ~
              site_domain
            ) | trim
          }}

    - name: Add the oneKE master to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "master_0"
        ansible_host: "{{ node_ips.master_0 }}"
        ansible_ssh_common_args: "-J jenkins@{{ bastion_ip }},root@{{ node_ips.vnf_0 }}"
        ansible_user: "root"

- name: "STAGE 2: Apply IaC to deploy the component"
  hosts: "master_0"
  gather_facts: false
  tasks:
    - name: Load enviromental variables from different sources inside the component
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Helm install
      vars:
        helm_release_name: "{{ hostvars['localhost']['entity_name'] | regex_replace('_', '') | lower }}"
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/any/cac/helm_install.yaml"


- name: "STAGE 3: Manipulate tn_bastion in order to enable communication to the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Set DNS record for the component
      ansible.builtin.uri:
        url: >-
          {{
            'http://' ~ bastion_ip ~ ':5380/api/zones/records/add?token=' ~ tn_dns_token ~
            '&domain=' ~ domain_name ~
            '&type=A&ptr=true&createPtrZone=true&ipAddress=' ~ node_ips.vnf_0 | trim
          }}
        method: POST
        body_format: json
        status_code: [200]
      register: dns_response
      until: dns_response.status == 200
      retries: 3
      delay: 10

    - name: Enable routes to the 5G Core AMF and UPF
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/routemanager_add.yaml"
      vars:
        endpoint: "{{ bastion_ip }}"
        token: "{{ tn_routemanager_token }}"
      loop:
        - { to: "{{ one_open5gs_k8s_amf_n2_ip }}", via: "{{ node_ips.vnf_0 }}" }
        - { to: "{{ one_open5gs_k8s_upf_n3_ip }}", via: "{{ node_ips.vnf_0 }}" }

    - name: Add tn_bastion to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "bastion"
        ansible_host: "{{ bastion_ip }}"
        ansible_user: "jenkins"


- name: "STAGE 4: Access tn_bastion to set firewall exceptions"
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Write firewall exceptions for the 5G Core AMF and UPF
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/nftables_add.yaml"
      vars:
        fw_exceptions:
          - "{{ one_open5gs_k8s_amf_n2_ip }}"
          - "{{ one_open5gs_k8s_upf_n3_ip }}"
        # nat_exceptions: ## TODO xception for amf_n2_ip/upf_n3_ip ?


- name: "STAGE 5: Publish execution results"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Define open5gs metadata dictionary
      ansible.builtin.set_fact:
        open5gs_metadata_dict: >-
          {
            'amf_n2_ip': '{{ one_open5gs_k8s_amf_n2_ip }}',
            'upf_n3_ip': '{{ one_open5gs_k8s_upf_n3_ip }}',
            'ue_count': '{{ one_open5gs_k8s_ue_count }}',
            'tac': '{{ one_open5gs_k8s_tac }}',
            'mcc': '{{ one_open5gs_k8s_mcc }}',
            'mnc': '{{ one_open5gs_k8s_mnc }}',
            'msin': '{{ one_open5gs_k8s_msin }}',
            'key': '{{ one_open5gs_k8s_key }}',
            'opc': '{{ one_open5gs_k8s_opc }}',
            'apn': '{{ one_open5gs_k8s_apn }}',
            's_nssai_sst': '{{ one_open5gs_k8s_s_nssai_sst }}',
            's_nssai_sd': '{{ one_open5gs_k8s_s_nssai_sd }}',
            'oneke': '{{ one_open5gs_k8s_target }}'
          }

    - name: Set custom terraform outputs for future components
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/custom_tf_outputs.yaml"
      vars:
        custom_outputs:
          - key: "{{ entity_name }}-metadata"
            value: "{{ open5gs_metadata_dict }}"

    - name: Publish execution results to TNLCM and S3 object storage
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/publish_ok_results.yaml"
