---
- name: Install some required apt packages
  become: true
  apt:
    name: 
      - net-tools
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Install docker engine
  block:
    - ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/docker_install.yaml"
  become: true

- name: Configure GitHub Container Registry authentication
  block:
    - ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/docker_configuration.yaml"
  become: true

- name: Copy docker-compose file
  copy:
    src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/docker-compose.yaml"
    dest: "/home/jenkins/docker-compose.yaml"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Copy static config folder recursively
  become: true
  ansible.builtin.copy:
    src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/config/static/"
    dest: "/home/jenkins/config"
    owner: jenkins
    group: jenkins
    mode: '0644'
    #directory_mode: '0755'

- name: Apply templates to configuration files
  template:
    src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/config/templates/{{ item.src }}"
    dest: "/home/jenkins/config/{{ item.dest }}"
    owner: jenkins
    group: jenkins
    mode: '0644'
  loop:
    - { src: 'open5gs/amf.yaml.j2', dest: 'open5gs/amf.yaml' }
    - { src: 'open5gs/nssf.yaml.j2', dest: 'open5gs/nssf.yaml' }
    - { src: 'open5gs/smf.yaml.j2', dest: 'open5gs/smf.yaml' }

- name: Execute docker-compose up
  become: true
  become_user: jenkins
  command: docker compose -f /home/jenkins/docker-compose.yaml up -d
  args:
    chdir: /home/jenkins

- name: Pause to wait for services deployment
  pause:
    seconds: 5

- name: Verify Open5GS services are running
  become: true
  become_user: jenkins
  command: docker ps --format '{{.Names}} - {{.Status}}'"
  register: docker_status
  changed_when: false
  failed_when: >
    'mongo - Up' not in docker_status.stdout or
    'amf - Up' not in docker_status.stdout or
    'ausf - Up' not in docker_status.stdout or
    'bsf - Up' not in docker_status.stdout or
    'nrf - Up' not in docker_status.stdout or
    'nssf - Up' not in docker_status.stdout or
    'pcf - Up' not in docker_status.stdout or
    'smf - Up' not in docker_status.stdout or
    'udm - Up' not in docker_status.stdout or
    'udr - Up' not in docker_status.stdout or
    'webui - Up' not in docker_status.stdout
    
- name: Verify specific Open5GS container health
  become: true
  become_user: jenkins
  command: "docker inspect -f '{{.State.Running}}' {{ item }}"
  loop:
    - mongo
    - amf
    - smf
    - nrf
    - ausf
    - udm
    - udr
    - pcf
    - nssf
    - bsf
    - webui
  register: container_status
  failed_when: "'true' not in container_status.stdout"

# TODO: At the moment, only one UE is registed
- name: Apply template to UEs registration script
  become: true
  become_user: jenkins
  template:
    src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/config/templates/register_subscriber.sh.j2"
    dest: "/home/jenkins/config/register_subscriber.sh"
    owner: jenkins
    group: jenkins
    mode: '0777'

- name: Run UE registration script
  #become: true
  #become_user: jenkins
  command: /home/jenkins/config/register_subscriber.sh
  register: ue_register_result
  failed_when: ue_register_result.rc != 0 and "duplicate key error" not in ue_register_result.stdout and "duplicate key error" not in ue_register_result.stderr


#TODO: NAT (future)?
