---
- name: "STAGE 1: Apply IAC to deploy the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Prepare terraform working directory
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_workdir.yaml"

    - name: Terraform apply
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_apply.yaml"


- name: "STAGE 2: Prepare to access the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Retrieve terraform outputs
      ansible.builtin.shell:
      args:
        chdir: "{{ workspace }}/.terraform/"
        cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
        executable: /bin/bash
      register: terraform_outputs
      changed_when: false

    - name: Set Terraform outputs as playbook facts
      ansible.builtin.set_fact:
        bastion_ip: "{{ (terraform_outputs.stdout | from_json)['tn_bastion-ips'][site_networks_id.default | string] }}"
        tn_ssh_public_key: "{{ (terraform_outputs.stdout | from_json)['tn_ssh_public_key'] }}"
        ips: "{{ (terraform_outputs.stdout | from_json)[entity_name + '-ips'] }}"
        id: "{{ (terraform_outputs.stdout | from_json)[entity_name + '-id'] }}"
        access_vnet_id: "{{ (terraform_outputs.stdout | from_json)[one_ks8500runner_networks[0] + '-id'] | string }}"

    - name: Add new VM to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "ks8500runner"
        ansible_host: "{{ ips[access_vnet_id] }}"
        ansible_ssh_common_args: "-J jenkins@{{ bastion_ip }}"
        ansible_user: "jenkins"

    - name: Add tn_bastion to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "bastion"
        ansible_host: "{{ bastion_ip }}"
        ansible_user: "jenkins"

    - name: Add new VM to SSH config file in the Jenkins-master for debugging purposes
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/jenkins_ssh_config.yaml"

    - name: Add new VM to an SSH config file ment to be usable by the experimenter
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/tnuser_ssh_config.yaml"

    # install passlib  
    - name: Install Passlib
      ansible.builtin.pip:
        name: passlib
        state: present
  
- name: "STAGE 3: Apply CAC to prepare the component"
  vars:
    ks8500runner_mounts:
      - Config
      - SessionLogs
      - Settings
      - Storage
      - OpentapImages
    home_path: /home/jenkins
    ks8500runner_path: "{{ home_path }}/runner"
    runner_dir: "{{ home_path }}/runner"   # change if you prefer another location
    zip_path: "{{ runner_dir }}/opentap.zip"
  hosts: "ks8500runner"
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        connect_timeout: 5
        timeout: 200

    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    # Some sites may have a MASTER ssh key, appart of the jenkins one
    - name: Set site ssh key as authorized in jenkins user
      ansible.posix.authorized_key:
        user: jenkins
        state: present
        key: "{{ item }}"
      loop:
        - "{{ hostvars['localhost'].get('site_admin_ssh_public_key', '') }}"
      when: item != ''

    - name: Ensure sudo package is installed
      become: true
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Set admin group based on OS family
      set_fact:
        admin_group: sudo    

    - name: Ensure admin group exists
      become: true
      ansible.builtin.group:
        name: "{{ admin_group }}"
        state: present

    - name: Enable admin group in sudoers
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "^%{{ admin_group }}"
        line: "%{{ admin_group }} ALL=(ALL) ALL"
        state: present
        validate: "visudo -cf %s"

    - name: Create new user for experimenter access
      become: true
      ansible.builtin.user:
        name: tnuser
        shell: /bin/bash
        groups: "{{ admin_group }}"
        append: yes
        password: "{{ 'keysight' | password_hash('sha256') }}"
        update_password: on_create

    # add public key to authorized keys list in tnuser
    - name: Set site ssh key as authorized in tnuser
      become: true
      ansible.posix.authorized_key:
        user: tnuser
        state: present
        key: "{{ item }}"
      loop:
        - "{{ hostvars['localhost']['tn_ssh_public_key']}}"
      when: item != ''  

      
    - name: Ensure tnuser has sudo privileges
      become: true
      ansible.builtin.user:
        name: tnuser
        groups: sudo        # or wheel on some systems
        append: yes
    
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
   
    - name: Wait for APT lock to be released
      become: true
      ansible.builtin.shell: |
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "APT lock detected, waiting..."
          sleep 30
        done
      changed_when: false
     
    - name: Install Python 3 and related packages
      become: true
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-requests
          - tshark 
          - libcap2-bin
        state: present
        
    - name: Ensure Wireshark config directory exists for jenkins
      file:
        path: /home/jenkins/.config/wireshark
        state: directory
        mode: '0755'
        
    - name: Copy Wireshark preferences file to jenkins (remote) 
      ansible.builtin.copy:
        src: all/runner/preferences          
        dest: /home/jenkins/.config/wireshark/preferences  # Path on the remote
        mode: '0644'

    - name: Copy Wireshark preferences file to system wide (remote)
      ansible.builtin.copy:
        src: all/runner/preferences          
        dest: /etc/wireshark/preferences  # Path on the remote
        owner: root
        group: root
        mode: '0644'
      become: true 

    # Detect if required network connectivity is available for the runner
    # Curl returns error if we cannot connect, should cause ansible script to terminate
    - name: Verify connectivity
      ansible.builtin.shell: curl "{{ks8500runner_backend_url}}/index.html"

    - name: Add Microsoft package repository GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      become: true        
    
    # Optional: skip if repo already installed
    - name: Check if Microsoft repo is already configured
      stat:
        path: "/etc/apt/sources.list.d/microsoft-prod.list"
      register: ms_repo_list
      become: true
      
    - name: Add Microsoft repo package
      apt:
        deb: "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
      when: not ms_repo_list.stat.exists
      become: true
      
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true
       
    - name: Install .NET SDK
      apt:
        name: dotnet-sdk-9.0
        state: present
      become: true

    - name: Verify .NET installation
      command: dotnet --version
      register: dotnet_version
      changed_when: false
      become: true
      
    - debug:
        msg: "Installed .NET version: {{ dotnet_version.stdout }}"

    
    - name: Ensure runner directory exists
      file:
        path: "{{ runner_dir }}"
        state: directory
        mode: "0755"
       
    - name: Download OpenTAP package zip
      get_url:
        url: "{{ opentap_url }}"
        dest: "{{ zip_path }}"
        mode: "0644"
        force: yes
    
    - name: Unpack OpenTAP into runner directory
      unarchive:
        src: "{{ zip_path }}"
        dest: "{{ runner_dir }}"
        remote_src: true

    - name: Remove zip after extraction
      file:
        path: "{{ zip_path }}"
        state: absent
      become: true

    - name: Ensure tap is executable
      file:
        path: "{{ runner_dir }}/tap"
        state: file
        mode: "0755"

    # ACL tooling is needed for switching to different users (become_user)
    #- name: Install ACL tooling
    #  ansible.builtin.package:
    #    name: acl
    #    state: present
    #  become: true
 
    - name: Ensure Ansible remote tmp exists for jenkins
      ansible.builtin.file:
        path: /home/jenkins/.ansible/tmp
        state: directory
        mode: "0700"       # strictly user-only
        
    - name: Install Runner image using tap
      command: ./tap image install "Runner:2.0.0"
      args:
        chdir: "{{ runner_dir }}"
        

    - name: Register runner with Keysight sandbox
      command: ./tap runner register --name {{ ks8500runner_name }} --url {{ ks8500runner_backend_url }} --token {{ ks8500runner_registration_token }}
      args:
        chdir: "{{ runner_dir }}"
      register: register_output

    - name: Add registration_info if available
      ansible.builtin.set_fact:
        ks8500runner_registration_info: "{{ register_output }}"
      when: register_output is defined  

    - name: Add registration_info if not available
      ansible.builtin.set_fact:
        ks8500runner_registration_info: "Registration not performed (already registered)"
      when: register_output is undefined

    - name: Install and start runner service
      command: ./tap runner service install -v --start-now
      args:
        chdir: "{{ runner_dir }}"

    - name: install Keysight IOLibrary 
      ansible.builtin.include_tasks: post_action_install_keysight_iolibrary.yaml
      when: ks8500runner_post_action is defined and ks8500runner_post_action == "install_keysight_iolibrary"     
      
- name: "STAGE 4: Access tn_bastion to set firewall exceptions"
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Write firewall exception for the Loadcore Middleware
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/nftables_add.yaml"
      vars:
        fw_exceptions:
          - "{{ site_available_components.ks8500_runner.loadcore_middleware_ip }}"


- name: "STAGE 5: Publish execution results"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Set custom terraform outputs for future components
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/custom_tf_outputs.yaml"
      vars:
        custom_outputs:
          - key: "registration_info"
            value: "{{ hostvars['ks8500runner']['ks8500runner_registration_info'] | b64encode }}"

    - name: Publish execution results to TNLCM and S3 object storage
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/publish_ok_results.yaml"
