---
- name: "STAGE 1: Apply IAC to deploy the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Prepare terraform working directory
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_workdir.yaml"

    - name: Terraform apply
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_apply.yaml"


- name: "STAGE 2: Prepare to access the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Retrieve terraform outputs
      ansible.builtin.shell:
      args:
        chdir: "{{ workspace }}/.terraform/"
        cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
        executable: /bin/bash
      register: terraform_outputs
      changed_when: false

    - name: Set Terraform outputs as playbook facts
      ansible.builtin.set_fact:
        bastion_ip: "{{ (terraform_outputs.stdout | from_json)['tn_bastion-ips'][site_networks_id.default | string] }}"
        tn_ssh_public_key: "{{ (terraform_outputs.stdout | from_json)['tn_ssh_public_key'] }}"
        ips: "{{ (terraform_outputs.stdout | from_json)[entity_name + '-ips'] }}"
        id: "{{ (terraform_outputs.stdout | from_json)[entity_name + '-id'] }}"
        access_vnet_id: "{{ (terraform_outputs.stdout | from_json)[one_ks8500runner_networks[0] + '-id'] | string }}"

    - name: Add new VM to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "ks8500runner"
        ansible_host: "{{ ips[access_vnet_id] }}"
        ansible_ssh_common_args: "-J jenkins@{{ bastion_ip }}"
        ansible_user: "jenkins"

    - name: Add tn_bastion to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "bastion"
        ansible_host: "{{ bastion_ip }}"
        ansible_user: "jenkins"

    - name: Add new VM to SSH config file in the Jenkins-master for debugging purposes
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/jenkins_ssh_config.yaml"

    - name: Add new VM to an SSH config file ment to be usable by the experimenter
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/tnuser_ssh_config.yaml"

    # install passlib  
    - name: Install Passlib
      ansible.builtin.pip:
        name: passlib
        state: present
  
- name: "STAGE 3: Apply CAC to prepare the component"
  vars:
    ks8500runner_mounts:
      - Config
      - SessionLogs
      - Settings
      - Storage
      - OpentapImages    
    #ks8500runner_path: /opt/KS8500Runner
    ks8500runner_path: /home/tnuser/runner
    opentap_url: "https://packages.opentap.io/4.0/Objects/Packages/OpenTAP?os=Linux&architecture=x64"
    runner_dir: /home/tnuser/runner   # change if you prefer another location
    zip_path: "{{ runner_dir }}/opentap.zip"
  hosts: "ks8500runner"
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        connect_timeout: 5
        timeout: 200

    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    # Some sites may have a MASTER ssh key, appart of the jenkins one
    - name: Set site ssh key as authorized in jenkins user
      ansible.posix.authorized_key:
        user: jenkins
        state: present
        key: "{{ item }}"
      loop:
        - "{{ hostvars['localhost'].get('site_admin_ssh_public_key', '') }}"
      when: item != ''

    - name: Ensure sudo package is installed
      become: true
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Set admin group based on OS family
      set_fact:
        admin_group: sudo    

    - name: Ensure admin group exists
      become: true
      ansible.builtin.group:
        name: "{{ admin_group }}"
        state: present

    - name: Enable admin group in sudoers
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "^%{{ admin_group }}"
        line: "%{{ admin_group }} ALL=(ALL) ALL"
        state: present
        validate: "visudo -cf %s"

    - name: Create new user for experimenter access
      become: true
      ansible.builtin.user:
        name: tnuser
        shell: /bin/bash
        groups: "{{ admin_group }}"
        append: yes
        password: "{{ 'keysight' | password_hash('sha256') }}"
        #password: 'keysight'
        update_password: on_create

    # add public key to authorized keys list in tnuser
    - name: Set site ssh key as authorized in tnuser
      become: true
      ansible.posix.authorized_key:
        user: tnuser
        state: present
        key: "{{ item }}"
      loop:
        - "{{ hostvars['localhost']['tn_ssh_public_key']}}"
      when: item != ''  

      
    - name: Ensure tnuser has sudo privileges
      become: true
      ansible.builtin.user:
        name: tnuser
        groups: sudo        # or wheel on some systems
        append: yes

    # Install additional packages
    #- name: Install additional required packages
    #  become: true
    #  ansible.builtin.package:
    #    name:
    #      - python3-pip
    #      - python3-requests
    #      - docker
    #      - docker-cli-buildx
    #      - docker-compose
    #      - openrc
    #      - docker-cli-compose
    #    state: present

    
    #- name: Enable Universe repository
    #  become: true
    #  ansible.builtin.command: add-apt-repository universe
    #  args:
    #    creates: /etc/apt/sources.list.d/universe.list
    
    #- name: Update apt cache
    #  become: true
    #  ansible.builtin.apt:
    #    update_cache: yes
   
    #- name: Add Docker official repo
    #  become: true
    #  ansible.builtin.shell: |
    #    apt-get update
    #    apt-get install -y ca-certificates curl gnupg
    #    install -m 0755 -d /etc/apt/keyrings
    #    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    #    echo \
    #      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    #      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
   
    - name: Wait for APT lock to be released
      become: true
      ansible.builtin.shell: |
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "APT lock detected, waiting..."
          sleep 30
        done
      changed_when: false
     
    - name: Install Python 3 and related packages
      become: true
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-requests
          #- docker-ce
          #- docker-ce-cli
          #- containerd.io
          #- docker-buildx-plugin
          #- docker-compose-plugin
        state: present

    # Detect if required network connectivity is available for the runner
    # Curl returns error if we cannot connect, should cause ansible script to terminate
    - name: Verify connectivity
      ansible.builtin.shell: curl https://6g-sandbox.automation.keysight.com/index.html

    # - name: Get os info
    #   command: cat /etc/os-release
    #   register: os_info

    # - name: List os info
    #   debug:
    #     msg: "{{ os_info.stdout }}"

    
    - name: Add Microsoft package repository GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      become: true        
    
    #- name: Ensure lsb-release is available
    #  apt:
    #    name: lsb-release
    #    state: present
    #    update_cache: yes
    #  become: true

    #- name: Get Ubuntu codename via lsb_release
    #  command: lsb_release -cs
    #  register: ubuntu_codename
    #  changed_when: false
    #  become: true

    #- debug:
    #    msg: "ubuntu codename: {{ ubuntu_codename.stdout }}"

    # Optional: skip if repo already installed
    - name: Check if Microsoft repo is already configured
      stat:
        path: "/etc/apt/sources.list.d/microsoft-prod.list"
      register: ms_repo_list
      become: true
      
    - name: Add Microsoft repo package
      apt:
        deb: "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
      when: not ms_repo_list.stat.exists
      become: true
      
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true
       
    - name: Install .NET SDK
      apt:
        name: dotnet-sdk-9.0
        state: present
      become: true

    
    - name: Verify .NET installation
      command: dotnet --version
      register: dotnet_version
      changed_when: false
      become: true
      
    - debug:
        msg: "Installed .NET version: {{ dotnet_version.stdout }}"

    - name: Ensure runner directory exists
      file:
        path: "{{ runner_dir }}"
        state: directory
        mode: "0755"
      become: true
      
    - name: Download OpenTAP package zip
      get_url:
        url: "{{ opentap_url }}"
        dest: "{{ zip_path }}"
        mode: "0644"
        force: yes
      become: true
       
    - name: Unzip OpenTAP into runner
      unarchive:
        src: "{{ zip_path }}"
        dest: "{{ runner_dir }}"
        remote_src: true
        keep_newer: true
      become: true
      
    - name: Remove zip after extraction
      file:
        path: "{{ zip_path }}"
        state: absent
      become: true

    
    - name: Ensure tap is executable
      file:
        path: "{{ runner_dir }}/tap"
        mode: "0755"
        state: file
      become: true
  
      
    - name: Install Runner image using tap
      command: ./tap image install "Runner:2.0.0"
      args:
        chdir: "{{ runner_dir }}"
      become: true  

    - name: Check if the registration file exists
      ansible.builtin.stat:
        path: "{{ ks8500runner_path }}/Config/runner.lic"
      register: registration_file
      become: true
   

    - name: Register runner with Keysight sandbox
      command: ./tap runner register --name {{ ks8500runner_name }} --url {{ ks8500runner_backend_url }} --token {{ ks8500runner_registration_token }}
      args:
        chdir: "{{ runner_dir }}"
      register: register_output
      when: not registration_file.stat.exists
      #become: true

    - name: Add registration_info if available
      ansible.builtin.set_fact:
        ks8500runner_registration_info: "{{ register_output }}"
      when: register_output is defined  

    - name: Add registration_info if not available
      ansible.builtin.set_fact:
        ks8500runner_registration_info: "Registration not performed (already registered)"
      when: register_output is undefined
   
    - name: Install and start runner service
      command: ./tap runner service install --start-now
      args:
        chdir: "{{ runner_dir }}"
      #become: true
   

    ################################### Docker Container starts ########################################

    #- name: Enable docker service
    #  ansible.builtin.service:
    #    name: docker
    #    state: started
    #    enabled: true
    #  become: true

    #- name: Delete runner data
    #  ansible.builtin.include_tasks: special_action_delete_runner_data.yaml
    #  when: ks8500runner_special_action is defined and ks8500runner_special_action == "delete_runner_data"

    #- name: Create runner dirs
    #  ansible.builtin.file:
    #    path: "{{ ks8500runner_path }}/{{ item }}"
    #    state: directory
    #    mode: '0700'
    #  loop: "{{ ks8500runner_mounts }}"
    #  become: true

    #- name: Deploy runner configuration
    #  ansible.builtin.copy:
    #    src: "{{ playbook_dir }}/all/runner/"
    #    dest: "{{ ks8500runner_path }}"
    #  become: true

    #- name: Build runner image
    #  community.docker.docker_image_build:
    #    name: ks8500_runner:latest
    #    path: "{{ ks8500runner_path }}"
    #    dockerfile: Dockerfile
    #  become: true

    #- name: Create mount list
    #  ansible.builtin.set_fact:
    #    mount_list: '{{ (mount_list|default([])) + [{"target": "/opt/tap/" + item, "source": "{{ ks8500runner_path }}/" + item, "type": "bind" }] }}'
    #  loop: "{{ ks8500runner_mounts }}"
    #  become: true
   
    # The microsoft base image uses this UID. Maybe we can find a better solution.
    #- name: Workaround permissions
    #  ansible.builtin.shell: "chown -R 1654:1654 {{ ks8500runner_path }}"
    #  become: true
    ################################### Docker Container ends ########################################
 
    # - name: Storage debug collect
    #   ansible.builtin.command:
    #     cmd: "ls -lR {{ ks8500runner_path }}"
    #   register: storage_debug
    #   become: true

    # - name: Storage debug out
    #   ansible.builtin.debug:
    #     var: storage_debug.stdout_lines

   
    #- name: Register runner
    #  community.docker.docker_container:
    #    image: ks8500_runner
    #    name: register-runner
    #    mounts: "{{ mount_list }}"
    #    entrypoint: ""
    #    detach: false
    #    working_dir: "{{ ks8500runner_path }}"
    #    command: /opt/tap/tap runner register --name {{ ks8500runner_name }} --url {{ ks8500runner_backend_url }} --token {{ ks8500runner_registration_token }}
    #  register: docker_container_output
    #  when: not registration_file.stat.exists
    #  become: true

    #- name: Start runner
    #  community.docker.docker_compose_v2:
    #    project_src: "{{ ks8500runner_path }}"
    #  become: true

  

- name: "STAGE 4: Access tn_bastion to set firewall exceptions"
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Write firewall exception for the Loadcore Middleware
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/nftables_add.yaml"
      vars:
        fw_exceptions:
          - "{{ site_available_components.ks8500_runner.loadcore_middleware_ip }}"


- name: "STAGE 5: Publish execution results"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Set custom terraform outputs for future components
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/custom_tf_outputs.yaml"
      vars:
        custom_outputs:
          - key: "registration_info"
            value: "{{ hostvars['ks8500runner']['ks8500runner_registration_info'] | b64encode }}"

    - name: Publish execution results to TNLCM and S3 object storage
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/publish_ok_results.yaml"
