---
- name: "STAGE 1: Apply IAC to deploy the component"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Prepare terraform working directory
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_workdir.yaml"

    - name: Terraform apply
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/terraform_apply.yaml"


- name: "STAGE 2: Prepare to access the tn_bastion"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Retrieve terraform outputs
      ansible.builtin.shell:
      args:
        chdir: "{{ workspace }}/.terraform/"
        cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
        executable: /bin/bash
      register: terraform_outputs
      changed_when: false

    - name: Set Terraform outputs as playbook facts
      ansible.builtin.set_fact:
        tn_vxlan_id: "{{ (terraform_outputs.stdout | from_json)['tn_vxlan-id'] }}"
        tn_bastion_ips: "{{ (terraform_outputs.stdout | from_json)['tn_bastion-ips'] }}"
        tn_bastion_id: "{{ (terraform_outputs.stdout | from_json)['tn_bastion-id'] }}"

    - name: Verify that the bastion access IP is correctly loaded
      ansible.builtin.debug:
        msg: "Network Main Interface is: {{ tn_bastion_ips[one_bastion_reachable_network] | default('----') }}"

    - name: Add new VM to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "tn_bastion"
        ansible_host: "{{ tn_bastion_ips[one_bastion_reachable_network] }}"

    - name: Create SSH config file in the Jenkins-master for debugging purposes
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/01_pre/ssh_config.yaml"


- name: "STAGE 3: Apply CAC to prepare the component"
  hosts: "tn_bastion"
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        connect_timeout: 5
        delay: 20
        timeout: 180

    ### Calling load_variables.yaml is unnecesary, as I can call localhost values with hostvars['localhost']['var_name'] or hostvars['localhost'].var_name"
    ### But it makes the code much MUCH cleaner with almost no extra latency
    - name: Load enviromental variables from different sources inside the component
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: Create an ed25519 ssh key pair to access the future Trial Network components
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/set_ssh_keypair.yaml"

    - name: Fetch VPN config
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/get_vpn_client_tunnel.yaml"
      when: site_hypervisor == "one"


- name: "STAGE 4: Publish execution results"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Publish SSH key as a terraform output
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/custom_tf_outputs.yaml"
      vars:
        custom_outputs:
          ssh_public_key: "{{ hostvars['tn_bastion']['ssh_public_key']['content'] | b64decode | trim }}"

    - name: Merge all component component outputs into one "output" variable
      ansible.builtin.set_fact:
        output:
          tn_vxlan_id: "{{ tn_vxlan_id | b64encode }}"
          tn_bastion_ips: "{{ tn_bastion_ips | b64encode }}"
          tn_bastion_id: "{{ tn_bastion_id | b64encode }}"
          vpn_client_tunnel: "{{ hostvars['tn_bastion']['client_tunnel']['content'] }}"
          ssh_public_key: "{{ hostvars['tn_bastion']['ssh_public_key']['content'] }}"
          ssh_private_key: "{{ hostvars['tn_bastion']['ssh_private_key']['content'] }}"

    - name: Publish execution results to TNLCM
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/publish_ok_results.yaml"
