################################################
##
## Component private variables
##
## Variables that should be necessary 
## for the deployment but are not available 
## to the experimenter
##
################################################

artifact_url: "https://marketplace.opennebula.io/appliance/84bd27fe-5d14-4e70-a79a-eb3fdd0072ae"
artifact_name: "UBUNTU XS"
