####################################
##
## Ansible YAML Playbook Template
## 
####################################
---
- name: "Setup Open5GCore on a Host"
  become: true
  vars:
    #gitlab_deploy_token: "" # Please define in inventory or cmdline! -e gitlab_deploy_token=foo
    ue_subnet: "{{ one_open5gcore_vm_ue_subnet | default('10.45.0.0/16') }}"
    mcc: "{{ one_open5gcore_vm_mcc | default('001') }}"
    mnc: "{{ one_open5gcore_vm_mnc | default('01') }}"
    msin: "{{ one_open5gcore_vm_msin | default('0000000001') }}"
    ue_key: "{{ one_open5gcore_vm_key | default('465B5CE8B199B49FAA5F0A2EE238A6BC') }}"
    ue_opc: "{{ one_open5gcore_vm_opc | default('E8ED289DEBA952E4283B54E88E6183CA') }}"
    ue_apn: "{{ one_open5gcore_vm_apn | default('internet') }}"
    ue_tac: "{{ one_open5gcore_vm_tac | default('200') }}"
    s_nssai_sst: "{{ one_open5gcore_vm_s_nssai_sst | default('1') }}"
    s_nssai_sd: "{{ one_open5gcore_vm_s_nssai_sd | default('000001') }}"
    #n2_ip: "{{ one_open5gcore_vm_amf_ip | default('10.10.10.2') }}"
    #n3_ip: "{{ one_open5gcore_vm_upf_ip | default('10.10.10.2') }}"
    n2_ip: "{{ ips_dict[1]['ip'] if ips_dict|length > 1 else ips_dict[0]['ip'] }}"
    ##
    n3_ip: "{{ ips_dict[2]['ip'] if ips_dict|length > 2 else ips_dict[1].ip if ips_dict|length > 1 else ips_dict[0]['ip'] }}"
    n3_if: "{{ 'eth2' if ips_dict|length > 2 else 'eth1' if ips_dict|length > 1 else 'eth0' }}"
    ##
    n6_ip: "{{ ips_dict[0]['ip'] }}"
    n6_if: "{{ 'eth0' }}"
    ##
    upf_xdp: "{{ one_open5gcore_vm_upf_xdp | default(false) }}"
    ue_count: "{{ one_open5gcore_vm_ue_count | default('20') }}"
    apt_upgrade: false
    playbookdir: "{{ workspace }}/{{ component_type }}/code/one/cac/02_install/"
  block:
    - name: Configure open5gcore
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/one/cac/02_install/configure-open5gcore.yml"