- name: Add routes in bastion
  vars:
    oneKE_vnf0_ip: "{{ hostvars['localhost']['node_ips'].get('vnf_0','') }}"
    o5gcore_ip: "{{ hostvars['localhost']['core_ips'][0]['ip'] if hostvars['localhost']['core_ips'] | length >=1 else '' }}"
    #next_hop_to_core: "{{ o5gcore_ip if o5gcore_ip|length>0 elif oneKE_vnf0_ip if oneKE_vnf0_ip|length>0 else '' }}"
  block:
    - name: add routes for oneKE
      become: yes
      ansible.builtin.shell: "ip route add {{ item }}"
      with_items:
        - "{{ site_available_components.berlin_ran.core_network }} via {{ oneKE_vnf0_ip }}"
        - "{{ site_available_components.berlin_ran.subnet }} via {{ site_available_components.berlin_ran.route_manager_ip1 }}"
      when: oneKE_vnf0_ip|length > 0

    - name: add route for 5g-core VM
      become: yes
      ansible.builtin.shell: "ip route add {{ item }}"
      with_items:
        - "{{ site_available_components.berlin_ran.core_network }} via {{ o5gcore_ip }}"
        - "{{ site_available_components.berlin_ran.subnet }} via {{ site_available_components.berlin_ran.route_manager_ip1 }}"
      when: o5gcore_ip | length > 0