---
- name: Install Python and pip
  ansible.builtin.apt:
    name: 
      - python3
      - python3-pip
    update_cache: true

- name: Install k8s python plugin
  ansible.builtin.pip:
    name:
      - kubernetes>12.0.0
      - pyyaml>=3.11
      - jsonpatch

- name: Install helm diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present