---
- name: Install Git and Clone Repo
  hosts: localhost
  become: true
  vars:
    repo: https://github.com/INFOLYSiS/opensand_config.git
    dest: "/home/repo"
  tasks:
    - name: Install git package
      ansible.builtin.package:
        name: git
        state: present