- name: Clone the repository
  ansible.builtin.git:
    repo_url: https://github.com/INFOLYSiS/opensand_config.git
    dest_dir: "/home/jenkins"
    version: "master"
  register: git_clone_result

- debug:
    var: git_clone_result