- name: Clone the repository
  become: true
  ansible.builtin.git:
    repo: "https://github.com/INFOLYSiS/opensand_config.git"
    dest: "/home/repo"
    version: "master"
  register: git_clone_result

- debug:
    var: git_clone_result
