---
- name: Install Git and Clone Repository
  become: true
  vars:
    repo_url: "https://github.com/INFOLYSiS/opensand_config.git"
    dest_dir: "/home/jenkins"
  tasks:
    - name: Install git package
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Clone the repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: "master"