- name: Clone the repository
  become: true
  vars:
    repo: https://github.com/INFOLYSiS/opensand_config.git
    dest: "/home/repo"
  tasks:  
  - ansible.builtin.git:
      repo: "{{ repo }}"
      dest: "{{ dest }}"
      version: "master"
  - register: git_clone_result

- debug:
    var: git_clone_result
