---
- name: Ensure .docker directory exists
  file:
    path: /home/jenkins/.docker
    state: directory
    mode: '0700'
    owner: jenkins
    group: jenkins

- name: Create Docker config file
  template:
    src: "{{ workspace }}/{{ component_type }}/code/one/cac/02_install/docker_config.json.j2"
    #src: docker_config.json.j2
    dest: /home/jenkins/.docker/config.json
    mode: '0600'
    owner: jenkins
    group: jenkins