---
- name: "Set VM Resources according to the instance type"
  ansible.builtin.set_fact:
    one_vm_kvm_cpu: "{{ one_vm_kvm_resources[one_vm_kvm_size].cpu }}"
    one_vm_kvm_memory: "{{ one_vm_kvm_resources[one_vm_kvm_size].memory }}"
    one_vm_kvm_disk: "{{one_vm_kvm_resources[one_vm_kvm_size].disk }}"

- name: Overwrite again with explicit values from the input file
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/input_file.yaml"
