- name: Add VM in SSH the configuration
  community.general.ssh_config:
    host: "{{ tn_id }}-oneke-{{ servicename }}-{{ role }}"
    hostname: "{{ ip }}"
    proxyjump: "{{tn_id}}-tn_bastion"
    remote_user: "root"
    ssh_config_file: "/var/lib/jenkins/.ssh/config.d/{{ tn_id }}"
    state: present
  when: role == "vnf"

- name: Add VM in SSH the configuration
  community.general.ssh_config:
    host: "{{ tn_id }}-oneke-{{ servicename }}-{{ role }}"
    hostname: "{{ ip }}"
    proxyjump: "{{tn_id}}-oneke-{{ servicename}}-vnf"
    remote_user: "root"
    ssh_config_file: "/var/lib/jenkins/.ssh/config.d/{{ tn_id }}"
    state: present
  when: role != "vnf"