---
- name: "Set VM Resources needed for Open5GS component"
  ansible.builtin.set_fact:
    one_upf_p4_hw_cpu: "{{ one_upf_p4_hw_open5gs_cpu }}"
    one_upf_p4_hw_memory: "{{ one_upf_p4_hw_open5gs_memory }}"
    one_upf_p4_hw_disk: "{{ one_upf_p4_hw_open5gs_disk }}"

- name: Overwrite again with explicit values from the input file
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/input_file.yaml"