################################################
##
## Component private variables
##
## Variables that should be necessary 
## for the deployment but are not available 
## to the experimenter
##
################################################

one_group: "oneadmin"   # change to "6G-Sandbox" in the future
one_vxlan_physical_device: "{{ site_vxlan_if }}"
one_vxlan_mtu: 1500
one_vxlan_guest_mtu: 1450
<<<<<<< HEAD
one_vxlan_security_groups: [100]
=======
one_vxlan_security_groups: [0]   # change to 100 in the future
one_vxlan_netmask: '255.255.255.0'
>>>>>>> main
