---
- name: "STAGE 1: Send API call to the RIS public endpoint"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Load enviromental variables from different sources
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/load_variables.yaml"

    - name: "Send POST request to a the RIS API"
      ansible.builtin.uri:
        url: "http://{{ site_available_components }}/api/set_codebook/"
        method: POST
        headers:
          accept: application/json
          # Authorization: "Bearer {{ token }}"
          Content-Type: application/json
        body_format: json
        body: |-
          {
            "f0": "{{ any_ris_f0 }}",
            "dist": "{{ any_ris_dist }}",
            "theta_t": "{{ any_ris_theta_t }}",
            "phi_t": "{{ any_ris_phi_t }}",
            "num_theta_r": {{ any_ris_num_theta_r }},
            "num_phi_r": {{ any_ris_num_phi_r }},
            "theta_r_low": "{{ any_ris_theta_r_low }}",
            "theta_r_high": "{{ any_ris_theta_r_high }}",
            "phi_r_low": "{{ any_ris_phi_r_low }}",
            "phi_r_high": "{{ any_ris_phi_r_high }}"
          }
        return_content: true
        status_code: [200, 201]
      register: api_response


- name: "STAGE 2: Publish execution results"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Set custom terraform outputs for future components
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/custom_tf_outputs.yaml"
      vars:
        custom_outputs:
          - key: "{{ entity_name }}-ip"
            value: "{{ site_available_components.ris.ip }}"
          - key: "{{ entity_name }}-f0"
            value: "{{ any_ris_f0 }}"
          - key: "{{ entity_name }}-dist"
            value: "{{ any_ris_dist }}"
          - key: "{{ entity_name }}-phi_t"
            value: "{{ any_ris_phi_t }}"
          - key: "{{ entity_name }}-theta_t"
            value: "{{ any_ris_theta_t }}"
          - key: "{{ entity_name }}-num_phi_r"
            value: "{{ any_ris_num_phi_r }}"
          - key: "{{ entity_name }}-phi_r_low"
            value: "{{ any_ris_phi_r_low }}"
          - key: "{{ entity_name }}-phi_r_high"
            value: "{{ any_ris_phi_r_high }}"
          - key: "{{ entity_name }}-num_theta_r"
            value: "{{ any_ris_num_theta_r }}"
          - key: "{{ entity_name }}-theta_r_low"
            value: "{{ any_ris_theta_r_low }}"
          - key: "{{ entity_name }}-theta_r_high"
            value: "{{ any_ris_theta_r_high }}"

    - name: Publish execution results to TNLCM and S3 object storage
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/publish_ok_results.yaml"
