---
- name: Append new commponent's name and IP into a .ssh/config.d/ file
  community.general.ssh_config:
    host: "{{ tn_id }}-{{ entity_name }}"
    # hostname:  "{{ ips[access_vnet_id] | default('ERROR_ASSIGNING_IP', true) }}"
    hostname: "{{ created_vm.instances[0].networks[0].ip }}"
    proxyjump: "{{ tn_id }}-tn_bastion"
    remote_user: "jenkins"
    ssh_config_file: "/var/lib/jenkins/.ssh/config.d/{{ tn_id }}"
    state: present
