---
- name: Append new commponent's name and IP into a .ssh/config.d/ file
  community.general.ssh_config:
    host: "{{ tn_id }}-{{ entity_name }}"
    hostname:  "{{ ips[access_vnet_id][0] | default('ERROR_ASSIGNING_IP', true) }}"
    proxyjump: "{{ tn_id }}-tn_bastion"
    remote_user: "jenkins"
    ssh_config_file: "/var/lib/jenkins/.ssh/config.d/{{ tn_id }}"
    state: present
  register: jenkins_ssh_config
