---
### Module community.general.ssh_config has limited options and doesnt allow to specify identity files that doesn't exist
- name: Append new commponent's name and IP into a .ssh/config.d/ file
  ansible.builtin.blockinfile:
    path: "{{ workspace }}/misc-{{ tn_id }}-ssh_config"
    block: |
      Host {{ tn_id }}-{{ entity_name }}-{{ item.key }}
          HostName {{ item.value | default('ERROR_ASSIGNING_IP', true) }}
          User tnuser
          IdentityFile ~/.ssh/misc-{{ tn_id }}-id_ed25519
          ProxyJump {% if item.key.startswith('vnf') %}{{ tn_id }}-tn_bastion{% else %}{{ tn_id }}-{{ entity_name }}-vnf_0{% endif %}
    marker: "# BEGIN {{ tn_id }}-{{ entity_name }} CONFIG"
    create: true
  register: tnuser_ssh_config
