---
### Module community.general.ssh_config has limited options and doesnt allow to specify identity files that doesn't exist
- name: Append new commponent's name and IP into a .ssh/config.d/ file
  ansible.builtin.blockinfile:
    path: "{{ workspace }}/misc-{{ tn_id }}-ssh_config"
    block: |
      Host {{ tn_id }}-{{ entity_name }}-{{ item.key }}
          HostName {{ item.value | default('ERROR_ASSIGNING_IP', true) }}
          User tnuser
          IdentityFile ~/.ssh/misc-{{ tn_id }}-id_ed25519
          {% if item.key.startswith('vnf') %}ProxyJump {{ tn_id }}-tn_bastion{% else %}{{ tn_id }}-{{ entity_name }}-vnf_0{% endif %}
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          LogLevel QUIET
    marker: "# {mark} {{ tn_id }}-{{ entity_name }}-{{ item.key }} CONFIG"
    insertafter: EOF
    create: true
  register: tnuser_ssh_config