---
- name: "Make a POST request to the tn_bastion's route-manager-api"
  ansible.builtin.uri:
    url: "http://{{ bastion_ip }}:8172/routes"
    method: POST
    headers:
      accept: application/json
      Authorization: "{{ site_available_components.site_routemanager.token }}"
      Content-Type: application/json
    body_format: json
    body: >
      {
        "destination": "{{ item.destination }}",
        "gateway": "{{ item.gateway }}",
        "create_at": "{{ nokia_radio_one_init_time }}",
        "delete_at": "{{ nokia_radio_one_end_time }}"
      }
    return_content: yes
  register: api_response
  loop:
  - { destination: "{{ site_available_components.nokia_radio.core_network }}", gateway: "{{ hostvars['localhost']['node_ips'].vnf_0 }}" }
  - { destination: "{{ site_available_components.nokia_radio.cp_ip }}", gateway: "{{ site_available_components.nokia_radio.route_manager_ip1 }}" }
  - { destination: "{{ site_available_components.nokia_radio.up_ip }}", gateway: "{{ site_available_components.nokia_radio.route_manager_ip1 }}" }

- name: Display response content
  debug:
    var: api_response.content