- name: Add routes in bastion
  ansible.builtin.shell: "ip route add {{ item }}"
  with_items:
    - "{{ nokia_radio_any_routable_network }} via {{ hostvars['localhost']['node_ips'].vnf_0 }}"
    - "{{ nokia_radio_one_main_ip }} via {{ nokia_radio_one_route_manager_ip }}"
  become: yes