---
- name: "Make a POST request to the site's route-manager-api"
  ansible.builtin.uri:
    url: "http://{{ site_available_components.site_routemanager.endpoint }}:8172/routes"
    method: POST
    headers:
      accept: application/json
      Authorization: "{{ site_available_components.site_routemanager.token }}"
      Content-Type: application/json
    body_format: json
    body: >
      {
        "destination": "{{ site_available_components.nokia_radio.core_network }}",
        "gateway": "{{ hostvars['localhost']['bastion_ip'] }}",
        "create_at": "{{ nokia_radio_one_init_time }}",
        "delete_at": "{{ nokia_radio_one_end_time }}"
      }
    return_content: yes
  register: api_response

- name: Display response content
  debug:
    var: api_response.content