---
- name: Run every task as root user
  become: true
  block:
    - name: Render netplan aliases
      ansible.builtin.template:
        src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/templates/99-netplan-aliases.yaml.j2"
        dest: /etc/netplan/99-netplan-aliases.yaml
        mode: '0600'
        backup: true
      register: netplan_changed

    - name: Reload netplan
      ansible.builtin.command:
        cmd: "netplan apply"
      changed_when: false
      when: netplan_changed.changed

    - name: Install MongoDB 6
      block:
        - name: Import MongoDB 6 public key
          ansible.builtin.get_url:
            url: https://pgp.mongodb.com/server-6.0.asc
            dest: /etc/apt/keyrings/mongodb-server-6.0.asc

        - name: Create MongoDB 6 repository list file
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/mongodb-server-6.0.asc] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse"
            state: present

        - name: Install mongodb-org package
          ansible.builtin.apt:
            name: "mongodb-org"
            update_cache: yes
            state: present

    - name: Open5GS stable version
      block:
        - name: Import Open5GS PPA repository
          ansible.builtin.apt_repository:
            repo: 'ppa:open5gs/latest'
            state: present

        - name: Install Open5GS 2.7.2~*
          ansible.builtin.apt:
            name: open5gs=2.7.2~*
            state: present
      when: not one_open5gs_vm_use_nightly

    - name: Open5GS nightly version
      block:
        - name: import nightly key
          ansible.builtin.get_url:
            url: https://obs.osmocom.org/projects/osmocom:nightly/public_key
            dest: /etc/apt/keyrings/open5gs-nightly.asc
            mode: 0600
          when: false
        - name: create key file
          ansible.builtin.copy:
            dest: /etc/apt/keyrings/open5gs-nightly.asc
            mode: '0755'
            content: |
              -----BEGIN PGP PUBLIC KEY BLOCK-----
              Version: GnuPG v1.4.5 (GNU/Linux)

              mQENBGKzE1QBCADFcM3ZzggvgxNRNNqDGWf5xIDAiK5qzFLdGes7L6F9VCHdaPy0
              RAOB5bFb/Q1tSDFNEBLtaauXKz+4iGL6qMVjZcyjzpB5w4jKN+kkrFRhjDNUv/SH
              BX6d+P7v5WBGSNArNgA8D1BGzckp5a99EZ0okMJFEqIcN40PD6OGugpq5XnVV5Nk
              e93fLa2Cu8vhFBcVn6CuHeEhsmuMf6NLbQRNfNNCEEUYaZn7beMYtpZ7t1djsKx5
              1xGm50OzI22FLu8lELQ9d7qMVGRG3WHYawX9BDteRybiyqxfwUHm1haWazRJtlGt
              UWyzvwAb80BK1J2Nu5fbAa3w5CoEPAbUuCyrABEBAAG0JW9zbW9jb20gT0JTIFBy
              b2plY3QgPG9zbW9jb21Ab3Ntb2NvbT6JAVQEEwEIAD4WIQRrKp83ktFetw1Oao+G
              pzC2U3JZcwUCZrNL8wIbAwUJCB7onwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAK
              CRCGpzC2U3JZc11RB/9oogcqTF30pPEwjjGvXF+WMiRFHl8aVvQIk9m+2KUcjlVk
              0q8+/guOg7KcVejPxyn2AQbTByWWgpH1o3BoDKWnvypURAV2uGOtCo6mUQop5yK0
              d50j9hwIXSwJWoD2r5OY+Gbs4dBzMGkKbnCED1n8324b8EN6m96eoL570Uq9vy4G
              gIp+QCpePu8AMdoCLR2w3J+TA4gLdDeH2cr7TgmwlDCp8e6R8FVmRt3SvunPmFz3
              FHDicv2f9ZoHXVLQ20DgWUyI1xOPlzBNJowgK9YnLPdIidE9i+EbvC1YA+6O/WMa
              kSUEyJLZS5mv2+T6ptgnCIgxrIoTu63O4Rsf5zV+iQEzBBMBCAAdFiEExoiYhHND
              S7aVYlnqa51NyAUyjdsFAmKzE1UACgkQa51NyAUyjdvuZgf+OXmr//i7u7Gg7eWB
              7e0qUsyCId9lXS8J437x3K6ciJfD7/6RSy8TFW5Nglm/uSkbyq582I8t+SoOirMD
              E6cg9U/5+h5s46bAf+Kd2XS/6tLGeNLM18i4el8CP06NpFzDrsKu76uYFpyRiiHD
              otBdtgxeLJ83LugGfZslF+/5cigJkAJMhAdVvGO8h85R6fba8ZSOKtMKkaQRfi76
              nhyOrJPlLuS+DLEnHwdkOFgtKnxHdjM97K+Tx0gisb6uwaWroXfSLnhP8RTLLZZy
              Z+noU1Hw3c+mn4c/NYbcC/uwHYHKRzuf9gHnQ3dGgv0Z5sbeLRVo92hjGj7Ftlyd
              4hmKBg==
              =5Cwc
              -----END PGP PUBLIC KEY BLOCK-----
        - name: add open5gs nightly repository file
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/open5gs-nightly.asc] https://downloads.osmocom.org/packages/osmocom:/nightly/xUbuntu_22.04/ ./"
            state: present
        - name: Install Open5GS nightly
          ansible.builtin.apt:
            name: open5gs
            state: latest
      when: one_open5gs_vm_use_nightly is defined and one_open5gs_vm_use_nightly

    - name: Install bmon
      ansible.builtin.apt:
        name: "bmon"
        state: present

    - name: Change Open5GS default configuration
      block:
        - name: Render NRF config
          ansible.builtin.template:
            src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/templates/open5gs/nrf.yaml.j2"
            dest: /etc/open5gs/nrf.yaml
            backup: true
          notify: Restart Open5GS

        - name: Fill in GTP Addresses in UPF config
          ansible.builtin.template:
            src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/templates/open5gs/upf.yaml.j2"
            dest: /etc/open5gs/upf.yaml
            backup: true
          notify: Restart Open5GS

        - name: Render AMF config
          ansible.builtin.template:
            src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/templates/open5gs/amf.yaml.j2"
            dest: /etc/open5gs/amf.yaml
            backup: true
          notify: Restart Open5GS

        - name: Render SMF config
          ansible.builtin.template:
            src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/templates/open5gs/smf.yaml.j2"
            dest: /etc/open5gs/smf.yaml
            backup: true
          notify: Restart Open5GS

        - name: Render NSSF config
          ansible.builtin.template:
            src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/templates/open5gs/nssf.yaml.j2"
            dest: /etc/open5gs/nssf.yaml
            backup: true
          notify: Restart Open5GS


    - name: Install Open5GS WebUI
      when: one_open5gs_vm_install_webui is defined and one_open5gs_vm_install_webui
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/install_webui.yaml"

    - name: Copy open5gs-dbctl
      ansible.builtin.copy:
        src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/files/open5gs-dbctl"
        dest: /usr/local/bin/
        mode: '0755'

    - name: Generate script add-test-ue.sh
      template:
        src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/templates/add-test-ues.sh.j2"
        dest: /etc/open5gs/add-test-ues.sh
        backup: true
        mode: '0755'
      register: add_ue_script

    - name: install testbed-sim-info
      ansible.builtin.copy:
        content: "{{ site_available_components.open5gs_vm.testbed_sim }}"
        dest: "/etc/open5gs/zz_testbed-sim.sh"
        mode: '0755'
      when: (site_available_components.open5gs_vm.testbed_sim is defined) and (site_available_components.open5gs_vm.testbed_sim|length > 0)
      register: testbed_simfile

    - name: Add UEs to UDM
      ansible.builtin.command:
        cmd: /etc/open5gs/add-test-ues.sh
      when: add_ue_script.changed

    - name: Add testbed-sim to UDM
      ansible.builtin.command:
        cmd: /etc/open5gs/zz_testbed-sim.sh
      when: testbed_simfile.changed

    - name: Render UE subnet into 99-open5gs.network
      template:
        src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/templates/99-open5gs.network.j2"
        dest: /etc/systemd/network/99-open5gs.network
        backup: true
      register: networkd_changed

    - name: Reload networkctl
      ansible.builtin.command:
        cmd: "networkctl reload"
      changed_when: false
      when: networkd_changed.changed

    - name: Disable UFW
      service:
        name: ufw
        state: stopped
        enabled: false

    - name: Copy sysctl.d/10-o5gc.conf
      ansible.builtin.copy:
        src: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/files/sysctl_10-5g_forward.conf"
        dest: /etc/sysctl.d/10-5g_forwarding.conf
      become: true

    - name: Reload sysctl
      ansible.builtin.command:
        cmd: "sysctl -w --system"
      changed_when: false

    - name: Disable Open5GS 4G parts
      ansible.builtin.systemd_service:
        state: stopped
        enabled: false
        name: "{{ item }}"
      loop:
        - open5gs-mmed
        - open5gs-sgwcd
        - open5gs-sgwud
