- name: Execute Install Vault Script
  ansible.builtin.shell: "/root/capif/helm/scripts/install_vault.sh"
  become: yes
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Fetch Vault keys file
  ansible.builtin.fetch:
    src: "capif/helm/vault_keys.txt"
    dest: "{{ workspace }}/{{ component_type }}/code/vault_keys.txt"
    flat: yes

  # ansible.builtin.copy:
  #   remote_src: true
  #   src: "capif/helm/vault_keys.txt"
  #   dest: "{{ workspace }}/{{ component_type }}/code/vault_keys.txt"
  #   mode: "644"