- name: Hello world
  ansible.builtin.shell: "echo \"HELLO\""
  become: yes

- name: Execute Install Vault Script
  ansible.builtin.script: "/root/capif/helm/scripts/install_vault.sh"
  # ansible.builtin.command: "/root/capif/helm/scripts/install_vault.sh"
  become: yes
