- name: Launch Robot OCF Testsuite
  ansible.builtin.shell: "capif/helm/scripts/run_remote_capif_tests.sh --include {{ ocf_any_tests_to_pass }}"
  become: true
  retries: 2
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Archive Robot OCF Testsuite results
  ansible.builtin.archive:
    path: capif/results
    dest: /tmp/ocf_robot_results.zip
    format: zip
    remove: yes

- name: Fetch and remove Robot Tests results
  block:
    - name: Fetch results
      ansible.builtin.fetch:
        src: /tmp/ocf_robot_results.zip
        dest: "{{ workspace }}/{{ component_type }}/code/ocf_robot_results.zip"
  # always:
  #   - name: Cleanup zip file
  #     ansible.builtin.file:
  #       path: /tmp/ocf_robot_results.zip
  #       state: absent
