- name: Launch Robot OCF Testsuite
  ansible.builtin.shell: "capif/helm/scripts/run_remote_capif_tests.sh --include smoke"
  become: yes
  retries: 2
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Compress Robot OCF Testsuite results
  ansible.builtin.shell: "zip -r ocf_robot_results.zip capif/results"
  become: yes

- name: Fetch Robot Tests results
  ansible.builtin.fetch:
    src: "ocf_robot_results.zip"
    dest: "{{ workspace }}/{{ component_type }}/code/ocf_robot_results.zip"
    flat: yes

- name: Remove Results directory
  ansible.builtin.shell: "rm -rf capif/results"
  become: yes