- name: Pause for 1 minutes to CAPIF get ready
  ansible.builtin.pause:
    minutes: 1

- name: Launch Robot OCF Testsuite
  ansible.builtin.shell: "capif/helm/scripts/run_remote_capif_tests.sh --include all"
  become: yes
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml