- name: Launch Robot OCF Testsuite
  ansible.builtin.shell: "capif/helm/scripts/create_remote_users.sh -u {{ ocf_user }} -p {{ ocf_password }} --include all"
  become: yes
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml