---
- name: "STAGE 1: Apply IAC to deploy the component"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Prepare terraform manifests
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/iac_tasks/prepare_one.yaml"
      when: site_hypervisor == "one"

    - name: Terraform apply
      community.general.terraform:
        project_path: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/iac/"
        state: "present"
        force_init: true
      ignore_errors: true
      register: terraform_apply


- name: "STAGE 2: Prepare to access the component"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Retrieve terraform output
      ansible.builtin.shell:
      args:
        chdir: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/iac/"
        cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
        executable: /bin/bash
      register: terraform_output
      changed_when: false
      when: not terraform_apply.failed

    - name: Set Terraform outputs as facts
      ansible.builtin.set_fact:
        bastion_ip: "{{ (terraform_output.stdout | from_json)['tn_bastion-ips']['0'] }}"
        ssh_public_key: "{{ (terraform_output.stdout | from_json)['ssh_public_key'] }}"
        id: "{{ (terraform_output.stdout | from_json)[entity_name + '-id'] }}"
        cluster_roles: "{{ (terraform_output.stdout | from_json)[entity_name + '-roles'] }}"
      when: not terraform_apply.failed

    - name: Fetch cluster node IDs
      ansible.builtin.set_fact:
        node_ids: "{{ node_ids | default({}) | combine({item.name: item.nodes[0]}) }}"
      loop: "{{ cluster_roles }}"
      when: item.nodes | length > 0

    - name: Fetch cluster node IPs
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/01_pre/node_ip.yaml"
      loop: "{{ node_ids | dict2items }}"


    - name: Add new VMs to Ansible Inventory
      ansible.builtin.add_host:
        hostname: "{{ entity_name }}-{{ item.key }}"
        ansible_host: "{{ item.value }}"
        ansible_ssh_common_args: "-J {{ site_jenkins_user }}@{{ bastion_ip }}{% if item.key != 'vnf' %},root@{{ node_ips.vnf }}{% else %}{% endif %}"
        ansible_user: "root"
      loop: "{{ node_ips | dict2items }}"

    - name: Add new VMs to SSH config file in the Jenkins-master for debugging purposes
      ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/01_pre/ssh_config.yaml"
      loop: "{{ node_ips | dict2items }}"

    - name: Fetch master metadata
      community.general.one_vm:
        instance_ids: "{{ node_ids.master | int }}"
      register: master_metadata
    - name: Extract kubeconfig file from master metadata
      ansible.builtin.set_fact:
        kubeconfig: "{{ master_metadata.instances[0].attributes.ONEKE_KUBECONFIG }}"

    - name: Create kubeconfig
      ansible.builtin.copy:
        content: "{{ kubeconfig | b64decode }}"
        dest: "{{ workspace }}/{{ component_type }}/code//{{ entity_name }}.kubeconfig"
        mode: "644"

- name: "STAGE 3: Apply CAC to prepare the component"
  hosts: "{{ hostvars['localhost']['entity_name'] }}-vnf,{{ hostvars['localhost']['entity_name'] }}-master,{{ hostvars['localhost']['entity_name'] }}-worker"
  gather_facts: false
  tasks:
    - name: Set the tn_id ssh key as authorized in the nodes
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ hostvars['localhost']['ssh_public_key'] }}"

    # - name: Find a free TCP port
    #   ansible.builtin.script:
    #     cmd: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/find_free_tcp_port.py"
    #     executable: /usr/bin/python3
    #   register: result_port

    # - name: Verify if port is empty
    #   ansible.builtin.assert:
    #     that: result_port.stdout | length > 0
    #     fail_msg: "There is not empty port"


### CONTINUE HERE. Conseguir que llegue al master sin ssh-config O!!! ejecutar los install directamente desde el master, when: inventory_hostname == hostvars['localhost']['entity_name'] + '-vnf'
    # - name: Start SSH tunnel if is not open
    #   ansible.builtin.shell: "ssh -f -L {{ result_port.stdout | trim }}:localhost:6443 {{ entity_name }}-master -N"
    #   when: result_port.stdout | length > 0

    # - name: Replace kubectl url endpoint
    #   ansible.builtin.replace:
    #     path: "{{ workspace }}/{{ component_type }}/private/{{ tn_id }}-oneke-{{ service_name }}.kubeconfig"
    #     regexp: "https://127.0.0.1:6443"
    #     replace: "https://127.0.0.1:{{ result_port.stdout | trim }}"

    - name: Apply extra Helm charts
      when: inventory_hostname == hostvars['localhost']['entity_name'] + '-vnf'
      block:
        - name: Post Actions ingress-nginx
          ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/install_nginx_controller.yaml"

        - name: Post Actions Skooner dashboard
          ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/install_skooner_dashboard.yaml"

        - name: Post Actions Longhorn dashboard
          ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/02_install/install_longhorn_dashboard.yaml"

    # - name: Delete previous SSH tunnel
    #   ansible.builtin.shell: "bash {{ workspace }}/.global/scripts/kill_ssh_jenkins.sh {{ result_port.stdout | trim }}"
    #   ignore_errors: true

# STAGE 5: Generate Responses and save manifest a config files
- name: Finishing deployment
  hosts: localhost
  tasks:

    # - name: Upload Kubeconfig to S3
    #   ansible.builtin.include_tasks: "{{ workspace }}/{{ component_type }}/code/{{ site_hypervisor }}/cac/03_post/kubeconfig_upload.yaml"
    - name: Upload kubeconfig to S3
      amazon.aws.s3_object:
        endpoint_url: "{{ site_s3_server.endpoint }}"
        mode: put
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')}}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY')}}"
        bucket: "{{ site_s3_server.bucket }}"
        object: "{{ tn_id }}/tf-{{ entity_name }}.tf"
        src: "{{ workspace }}/{{ component_type }}/code//{{ entity_name }}.kubeconfig"
        encrypt: no

    - name: Merge all component component outputs into one "output" variable
      ansible.builtin.set_fact:
        output:
          id: "{{ id | b64encode }}"
          cluster_roles: "{{ cluster_roles | b64encode }}"
          node_ids: "{{ node_ids | b64encode }}"
          node_ips: "{{ node_ips | b64encode }}"
          kubeconfig: "{{ kubeconfig }}"
          skooner_token: "{{ hostvars[entity_name + '-master']['skooner_token']['stdout'] | b64encode }}"
      when: not terraform_apply.failed

    - name: Publish execution results to TNLCM
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/common_tasks/publish_results.yaml"

    - name: Upload markdown info to S3 storage
      ansible.builtin.include_tasks: "{{ workspace }}/.global/cac/common_tasks/s3_upload.yaml"
      when: not terraform_apply.failed
