---
- name: Retrieve terraform outputs from previous components
  ansible.builtin.shell:
  args:
    chdir: "{{ workspace }}/.terraform/"
    cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
    executable: /bin/bash
  register: terraform_outputs
  changed_when: false

- name: Tasks for UERANSIM as gNB
  when: one_ueransim_run_gnb == 'YES'
  block:
    - name: Convert open5gs terraform output to a dictionary
      set_fact:
        open5gs_metadata_dict: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_gnb_linked_open5gs + '-metadata'] }}"

    - name: Overwrite gNB-related variables
      ansible.builtin.set_fact:
        one_ueransim_gnb_amf_ip: "{{ open5gs_metadata_dict.amf_ip }}"
        one_ueransim_gnb_amf_proxy: "{{ open5gs_metadata_dict.proxy }}"
        one_ueransim_gnb_tac:  "{{ open5gs_metadata_dict.tac }}"
        one_ueransim_gnb_mcc:  "{{ open5gs_metadata_dict.mcc }}"
        one_ueransim_gnb_mnc:  "{{ open5gs_metadata_dict.mnc }}"
        one_ueransim_gnb_msin: "{{ open5gs_metadata_dict.msin }}"  # Not used by the gNB, but required for UE autocompletion
        one_ueransim_gnb_key:  "{{ open5gs_metadata_dict.key }}"   # Not used by the gNB, but required for UE autocompletion
        one_ueransim_gnb_opc:  "{{ open5gs_metadata_dict.opc }}"   # Not used by the gNB, but required for UE autocompletion
        one_ueransim_gnb_apn:  "{{ open5gs_metadata_dict.apn }}"   # Not used by the gNB, but required for UE autocompletion
        one_ueransim_gnb_slices_sst: "{{ open5gs_metadata_dict.s_nssai_sst }}"
        one_ueransim_gnb_slices_sd:  "{{ open5gs_metadata_dict.s_nssai_sd }}"


- name: Tasks for UERANSIM as UE with external gNB
  when:
    - one_ueransim_run_ue == 'YES'
    - one_ueransim_run_gnb == 'NO'
  block:
    - name: Create variables for gNB from terraform outputs
      set_fact:
        access_vnet_id: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_networks[0] + '-id'] | string }}"
        gnb_ips: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-ips'] }}"
        gnb_metadata_dict: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-gnb_metadata'] }}"

    - name: Overwrite UE-related variables when gNB is in another component
      ansible.builtin.set_fact:
        one_ueransim_ue_gnbSearchList: ["{{ gnb_ips[access_vnet_id] }}"]
        one_ueransim_ue_mcc:  "{{ gnb_metadata_dict.mcc }}"
        one_ueransim_ue_mnc:  "{{ gnb_metadata_dict.mnc }}"
        one_ueransim_ue_msin: "{{ gnb_metadata_dict.msin }}"
        one_ueransim_ue_key:  "{{ gnb_metadata_dict.key }}"
        one_ueransim_ue_opc:  "{{ gnb_metadata_dict.opc }}"
        one_ueransim_ue_session_apn: "{{ gnb_metadata_dict.apn }}"
        one_ueransim_ue_session_sst: "{{ gnb_metadata_dict.sst }}"
        one_ueransim_ue_session_sd:  "{{ gnb_metadata_dict.sd }}"


- name: Overwrite UE-related variables when gNB is in the same component
  when:
    - one_ueransim_run_ue == 'YES'
    - one_ueransim_run_gnb == 'YES'
  ansible.builtin.set_fact:
    one_ueransim_ue_linked_gnb: "{{ entity_name }}"
    one_ueransim_ue_gnbSearchList: "localhost"
    one_ueransim_ue_mcc:  "{{ one_ueransim_gnb_mcc | default(open5gs_metadata_dict.mcc, true) }}"
    one_ueransim_ue_mnc:  "{{ one_ueransim_gnb_mnc | default(open5gs_metadata_dict.mnc, true) }}"
    one_ueransim_ue_msin: "{{ open5gs_metadata_dict.msin }}"
    one_ueransim_ue_key:  "{{ open5gs_metadata_dict.key }}"
    one_ueransim_ue_opc:  "{{ open5gs_metadata_dict.opc }}"
    one_ueransim_ue_session_apn: "{{ open5gs_metadata_dict.apn }}"
    one_ueransim_ue_session_sst: "{{ one_ueransim_gnb_slices_sst | default(open5gs_metadata_dict.sst, true) }}"
    one_ueransim_ue_session_sd:  "{{ one_ueransim_gnb_slices_sd | default(open5gs_metadata_dict.sd, true) }}"

  
- name: Overwrite autocompleted values again with explicit values from the input file
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/input_file.yaml"
