---
- name: Retrieve terraform outputs from previous components
  ansible.builtin.shell:
  args:
    chdir: "{{ workspace }}/.terraform/"
    cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
    executable: /bin/bash
  register: terraform_outputs
  changed_when: false

- name: Overwrite the run variables according to the mode
  ansible.builtin.set_fact:
    one_ueransim_run_gnb: "{{ one_ueransim_mode in ['gnb', 'both'] }}"
    one_ueransim_run_ue: "{{ one_ueransim_mode in ['ue', 'both'] }}"

- name: Autocompletion tasks for UERANSIM as gNB
  when:
    - one_ueransim_mode in ['gnb', 'both']
    - (one_ueransim_gnb_linked_5gcore | default('') | length > 0)
  block:
    - name: Validate the provided 5G core for autocompletion
      vars:
        valid_component_types: ['open5gcore_vm', 'open5gs_k8s', 'open5gs_vm', 'upf_p4_sw']
      ansible.builtin.assert:
        that:
          - (terraform_outputs.stdout | from_json)[one_ueransim_gnb_linked_5gcore + '-component_type'] in valid_component_types
        fail_msg: "The 5G core: {{ one_ueransim_gnb_linked_5gcore }} is undefined or invalid for variable autocompletion."

    - name: Convert the 5G core terraform outputs into a metadata dictionary
      ansible.builtin.set_fact:
        core_metadata: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_gnb_linked_5gcore + '-5gcore_metadata'] }}"

    - name: Autocomplete gNB-related variables
      ansible.builtin.set_fact:
        one_ueransim_gnb_amf_n2_ip: "{{ core_metadata.amf_n2_ip | default(omit) }}"
        one_ueransim_gnb_tac: "{{ core_metadata.tac | default(omit) }}"
        one_ueransim_gnb_mcc: "{{ core_metadata.mcc | default(omit) }}"
        one_ueransim_gnb_mnc: "{{ core_metadata.mnc | default(omit) }}"
        one_ueransim_gnb_slices_sst: "{{ core_metadata.s_nssai_sst | default(omit) }}"
        one_ueransim_gnb_slices_sd: "{{ core_metadata.s_nssai_sd | default(omit) }}"

    - name: Only in mode **both**, aditionally autocomplete UE-related variables with the linked 5G core metadata
      when:
        - one_ueransim_mode == 'both'
      ansible.builtin.set_fact:
        one_ueransim_ue_gnbsearchlist: "localhost"
        one_ueransim_ue_mcc: "{{ core_metadata.mcc | default(omit) }}"
        one_ueransim_ue_mnc: "{{ core_metadata.mnc | default(omit) }}"
        one_ueransim_ue_msin: "{{ core_metadata.msin | default(omit) }}"
        one_ueransim_ue_key: "{{ core_metadata.key | default(omit) }}"
        one_ueransim_ue_opc: "{{ core_metadata.opc | default(omit) }}"
        one_ueransim_ue_session_apn: "{{ core_metadata.apn | default(omit) }}"
        one_ueransim_ue_session_sst: "{{ core_metadata.s_nssai_sst | default(omit) }}"
        one_ueransim_ue_session_sd: "{{ core_metadata.s_nssai_sd | default(omit) }}"


  # Including both here makes little sense, but someone might want to let the UE ignore the internal gNB and use another one
- name: Autocompletion tasks for UERANSIM as UE with external gNB
  when:
    - one_ueransim_mode in ['ue', 'both']
    - (one_ueransim_ue_linked_gnb | default('') | length > 0)
  block:
    - name: Validate the provided UERANSIM gNB for autocompletion
      when: (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-component_type'] == 'ueransim'
      ansible.builtin.assert:
        that: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-mode'] in ['gnb', 'both'] }}"
        fail_msg: "The provided UERANSIM: {{ one_ueransim_ue_linked_gnb }} is not in a gNB-enabled mode."

    - name: Convert the linked terraform output of the 5G core of the linked gNB into a metadata dictionary
      vars:
        gnb_linked_core: "{{ ((terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-gnb_metadata'] | from_yaml)['linked_5gcore'] }}"
      ansible.builtin.set_fact:
        core_metadata: "{{ (terraform_outputs.stdout | from_json)[gnb_linked_core + '-5gcore_metadata'] }}"

    - name: Set gNB address for UE mode
      when: one_ueransim_mode == 'ue'
      ansible.builtin.set_fact:
        access_vnet_id: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_networks[0] + '-id'] | string }}"
        gnb_ips: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-ips'] }}"

    - name: Autocomplete UE-related variables
      ansible.builtin.set_fact:
        one_ueransim_ue_gnbsearchlist: "{{ (gnb_ips | default({})).get(access_vnet_id) | default(omit) }}"
        one_ueransim_ue_mcc: "{{ core_metadata.mcc | default(omit) }}"
        one_ueransim_ue_mnc: "{{ core_metadata.mnc | default(omit) }}"
        one_ueransim_ue_msin: "{{ core_metadata.msin | default(omit) }}"
        one_ueransim_ue_key: "{{ core_metadata.key | default(omit) }}"
        one_ueransim_ue_opc: "{{ core_metadata.opc | default(omit) }}"
        one_ueransim_ue_session_apn: "{{ core_metadata.apn | default(omit) }}"
        one_ueransim_ue_session_sst: "{{ core_metadata.s_nssai_sst | default(omit) }}"
        one_ueransim_ue_session_sd: "{{ core_metadata.s_nssai_sd | default(omit) }}"


- name: "In mode **both**, set variable 'one_ueransim_ue_linked_gnb' as itself when variable is left undefined"
  when:
    - one_ueransim_mode == 'both'
    - (one_ueransim_ue_linked_gnb | default('') | length == 0)
  ansible.builtin.set_fact:
    one_ueransim_ue_linked_gnb: "{{ entity_name }}"

- name: Overwrite autocompleted values again with explicit values from the input file
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/input_file.yaml"