---
- name: Retrieve terraform outputs from previous components
  ansible.builtin.shell:
  args:
    chdir: "{{ workspace }}/.terraform/"
    cmd: "set -o pipefail && terraform output --json | jq 'with_entries(.value |= .value)'"
    executable: /bin/bash
  register: terraform_outputs
  changed_when: false

- name: Overwrite the run variables according to the mode
  ansible.builtin.set_fact:
    one_ueransim_run_gnb: "{{ one_ueransim_mode in ['gnb', 'both'] }}"
    one_ueransim_run_ue: "{{ one_ueransim_mode in ['ue', 'both'] }}"

- name: Autocompletion tasks for UERANSIM as gNB
  when:
    - one_ueransim_mode in ['gnb', 'both']
    - one_ueransim_gnb_linked_5gcore is defined
    - one_ueransim_gnb_linked_5gcore != ''
  block:
    - name: Validate the provided 5G core for autocompletion
      vars:
        valid_component_types: ['open5gcore_vm', 'open5gs_k8s', 'open5gs_vm', 'upf_p4_sw']
      ansible.builtin.fail:
        msg: "The 5G core: {{ one_ueransim_gnb_linked_5gcore }} is not valid for variable autocompletion."
      when: >
        (
          (terraform_outputs.stdout | from_json)[one_ueransim_gnb_linked_5gcore + '-component_type'] not in valid_component_types
        )

    - name: Convert 5G core terraform outputs to a dictionary
      ansible.builtin.set_fact:
        5gcore_metadata_dict: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_gnb_linked_5gcore + '-5gcore_metadata'] }}"

    - name: Autocomplete gNB-related variables
      ansible.builtin.set_fact:
        one_ueransim_gnb_amf_n2_ip: "{{ 5gcore_metadata_dict.amf_n2_ip }}"
        one_ueransim_gnb_tac: "{{ 5gcore_metadata_dict.tac }}"
        one_ueransim_gnb_mcc: "{{ 5gcore_metadata_dict.mcc }}"
        one_ueransim_gnb_mnc: "{{ 5gcore_metadata_dict.mnc }}"
        one_ueransim_gnb_msin: "{{ 5gcore_metadata_dict.msin | default('None') }}"  # Not used by the gNB, but required for UE autocompletion
        one_ueransim_gnb_key: "{{ 5gcore_metadata_dict.key  | default('None') }}"   # Not used by the gNB, but required for UE autocompletion
        one_ueransim_gnb_opc: "{{ 5gcore_metadata_dict.opc  | default('None') }}"   # Not used by the gNB, but required for UE autocompletion
        one_ueransim_gnb_apn: "{{ 5gcore_metadata_dict.apn  | default('None') }}"   # Not used by the gNB, but required for UE autocompletion
        one_ueransim_gnb_slices_sst: "{{ 5gcore_metadata_dict.s_nssai_sst }}"
        one_ueransim_gnb_slices_sd: "{{ 5gcore_metadata_dict.s_nssai_sd }}"


  # Outside the previous block to support rogue users that may specify mode 'both' without a linked_5gcore, while only providing input for the gNB variables.
- name: Autocompletion tasks for UERANSIM as UE with internal gNB
  when:
    - one_ueransim_mode in 'both'
  block:
    - name: Autocomplete UE-related variables with the internal gNB
      ansible.builtin.set_fact:
        one_ueransim_ue_linked_gnb: "{{ entity_name }}"
        one_ueransim_ue_gnbsearchlist: 'localhost'
        one_ueransim_ue_mcc: "{{ one_ueransim_gnb_mcc }}"
        one_ueransim_ue_mnc: "{{ one_ueransim_gnb_mnc }}"
        one_ueransim_ue_msin: "{{ one_ueransim_gnb_msin | default(omit) }}"
        one_ueransim_ue_key: "{{ one_ueransim_gnb_key | default(omit) }}"
        one_ueransim_ue_opc: "{{ one_ueransim_gnb_opc | default(omit) }}"
        one_ueransim_ue_session_apn: "{{ one_ueransim_gnb_apn | default(omit) }}"
        one_ueransim_ue_session_sst: "{{ one_ueransim_gnb_slices_sst }}"
        one_ueransim_ue_session_sd: "{{ one_ueransim_gnb_slices_sd }}"


- name: Autocompletion tasks for UERANSIM as UE with external gNB
  when:
    - one_ueransim_mode in 'ue'
    - one_ueransim_gnb_linked_gnb is defined
    - one_ueransim_gnb_linked_gnb != ''
  block:
    - name: Validate the provided gNB for autocompletion
      vars:
        valid_component_types: ['berlin_ran', 'hw_gNB', 'iswireless_radio', 'nokia_radio', 'ueransim']
      ansible.builtin.fail:
        msg: "The gnB: {{ one_ueransim_ue_linked_gnb }} is not valid for variable autocompletion."
      when: >
        (
          (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-component_type'] not in valid_component_types
        )
        or
        (
          (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-component_type'] == 'ueransim'
          and
          (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-mode'] not in ['both', 'gnb']
        )

    - name: Create intermediate gNB variables from terraform outputs
      set_fact:
        access_vnet_id: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_networks[0] + '-id'] | string }}"
        gnb_ips: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-ips'] }}"
        gnb_metadata_dict: "{{ (terraform_outputs.stdout | from_json)[one_ueransim_ue_linked_gnb + '-gnb_metadata'] }}"

    - name: Autocomplete UE-related variables
      ansible.builtin.set_fact:
        one_ueransim_ue_gnbsearchlist: "{{ gnb_ips[access_vnet_id] }}"
        one_ueransim_ue_mcc: "{{ gnb_metadata_dict.mcc }}"
        one_ueransim_ue_mnc: "{{ gnb_metadata_dict.mnc }}"
        one_ueransim_ue_msin: "{{ gnb_metadata_dict.msin | default(omit) }}"
        one_ueransim_ue_key: "{{ gnb_metadata_dict.key  | default(omit) }}"
        one_ueransim_ue_opc: "{{ gnb_metadata_dict.opc  | default(omit) }}"
        one_ueransim_ue_session_apn: "{{ gnb_metadata_dict.apn  | default(omit) }}"
        one_ueransim_ue_session_sst: "{{ gnb_metadata_dict.sst }}"
        one_ueransim_ue_session_sd: "{{ gnb_metadata_dict.sd }}"

- name: Overwrite autocompleted values again with explicit values from the input file
  ansible.builtin.include_vars:
    file: "{{ workspace }}/{{ component_type }}/variables/input_file.yaml"
